### PR TITLE
SqlServiceAccount: Corrected issue with detecting service names

### LINKED ISSUE #930: xSQLServerServiceAccount: The ReportingServices service could not be found
## **Details of the scenario you tried and the problem that is occurring:**

I have a two server setup:
- Server One running "SQLENGINE" and "SSMS" features
- Server Two running **only** "RS" feature

I am using xSQLSeverSetup to install on both machines (which works fine). I am **not** setting the RSSvcAccount property on xSQLServerSetup. Rather, I am attempting to use xSQLServerServiceAccount to set the account for the Server running **RS**. 

However, this fails with the following error message:
```
PowerShell DSC resource MSFT_xSQLServerServiceAccount  failed to execute Test-TargetResource functionality with error
message: System.Exception: The ReportingServices service on SSRS\MSSQLSERVER could not be found.
    + CategoryInfo          : InvalidOperation: (:) [], CimException  
```

Reporting Services is installed and can be accessed via the Configuration Manager with the Server Name (SSRS) and instance (MSSQLSERVER) listed in the error message. For example:

ssrs

The error looks like it originates from the [Get-ServiceObject ](https://github.com/PowerShell/SqlServerDsc/blob/b3335654581de3035c7b0a6f37f2b280eb749e2c/DSCResources/MSFT_SqlServiceAccount/MSFT_SqlServiceAccount.psm1) function...

When I manually execute this (and substitute the values) it does not find the the ReportServer service. However, if I remove the **-and** clause from the line that searches through $managedComputer.Services, then it does work and returns the ReportServer service.

```powershell
# Get the Service object for the specified instance/type
function Get-ServiceObject 
{
...
# Connect to SQL WMI
$managedComputer = New-Object Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer $SQLServer

# Change the regex pattern for a default instance
if ($SQLInstanceName -ieq 'MSSQLServer')
{
    $serviceNamePattern = '^MSSQLServer$'
}
else
{
    $serviceNamePattern = ('\${0}$' -f $SQLInstanceName)
}

# Get the proper enum value
$serviceTypeFilter = ConvertTo-ManagedServiceType -ServiceType $ServiceType

# Get the Service object for the specified instance/type
$serviceObject = $managedComputer.Services | Where-Object -FilterScript {
    ($_.Type -eq $serviceTypeFilter) -and ($_.Name -imatch $serviceNamePattern)
}
...
```
So, perhaps something up with the regex? Or, is it possible I am not passing the right value to SQLInstanceName? Or, could it be something unexpected with my install?

## **The DSC configuration that is using the resource (as detailed as possible):**

```powershell
# by default, reporting services can't create databases on other machines, to work
# around that we can change it to use either Network Serivce or a Domain Account
# https://docs.microsoft.com/en-us/sql/reporting-services/install-windows/install-reporting-services

$dummyPass = ConvertTo-SecureString "dummy" -AsPlainText -Force
$rsServiceCreds = New-Object System.Management.Automation.PSCredential ("NT AUTHORITY\NETWORK SERVICE", $dummyPass)

xSQLServerServiceAccount SetRSServiceAcccount
{
    SQLServer = $NodeName
    SQLInstanceName = $SqlData.InstanceName
    ServiceType = "ReportingServices"
    ServiceAccount = $rsServiceCreds
    DependsOn = "[xSqlServerSetup]InstallSql", "[File]InstallSqlServerModule"
}
# NOTE 
# $NodeName evaluates to "SSRS"
# $SqlData.InstanceName evaluates to "MSSQLSERVER"
```
**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Windows Server 2012R2, SQL Server 2014 SP2, PowerShell5.1

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
SqlServer 21.0.17199

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
9.0.0.0

### PR DESCRIPTION
**Pull request by nabrond**
**Pull Request (PR) description**
Corrected an issue with `SqlServiceAccount` where default services were not properly detected.

**This Pull Request (PR) fixes the following issues:**

Fixes #930 

**Task list:**

- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/947)

### CODE REVIEW

**Comment by johlju** [comment]
I got stuck with the flu, so will review this once my head is back in the game again. :)

**Comment by johlju** [comment]
@nabrond Great work! Just minor stuff, and need a rebase on this one to fix the CHANGELOG.md. 

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1, line 413 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-L0YkDgVVOR4uzMgFy4e:-L0YkDgVVOR4uzMgFy4f:b-nilczb) ([raw file](https://github.com/powershell/sqlserverdsc/blob/d5bbb39d7efc1374837bf4874bd4c681e4475796/Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1#L413)):*
> ```PowerShell
> 
>         Describe 'MSFT_SqlServerServiceAccount\Get-SqlServiceName' -Tag 'Helper' {
>             Mock @mockGetChildItemParameters
> ```

Minor: Maybe add this in a BeforeAll-block, beneath the two context block's below. Then the mock is not available in the third Context-block where "NoServices" are  evaluated.

---

*[Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1, line 505 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-L0Yl9fmzj8rNnrhXPMs:-L0Yl9fmzj8rNnrhXPMt:bnpnf21) ([raw file](https://github.com/powershell/sqlserverdsc/blob/d5bbb39d7efc1374837bf4874bd4c681e4475796/Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1#L505)):*
> ```PowerShell
>                         @{
>                             ServiceType = 'IntegrationServices'
>                             # ExpectedServiceName = ('{0}' -f $mockNamedInstance)
> ```

Remove this row since it is commented?

---

*[Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1, line 509 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-L0YlDO4rkly7eOaJGeD:-L0YlDO4rkly7eOaJGeE:bnpnf21) ([raw file](https://github.com/powershell/sqlserverdsc/blob/d5bbb39d7efc1374837bf4874bd4c681e4475796/Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1#L509)):*
> ```PowerShell
>                         @{
>                             ServiceType = 'SQLServerBrowser'
>                             # ExpectedServiceName = ('{0}' -f $mockNamedInstance)
> ```

Remove this row since it is commented?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-:-L0YfTINXE6W2NDnAuH9:bkgirc6)*

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1, line 465 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-L0ZMQtVQygvkASg7XoV:-L0ZMQtVQygvkASg7XoW:b-208pct) ([raw file](https://github.com/powershell/sqlserverdsc/blob/d5bbb39d7efc1374837bf4874bd4c681e4475796/Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1#L465)):*
> Should Be

New format: `Should -Be`

---

*[Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1, line 527 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-L0ZM_Xp7KXbWmx3W0Cr:-L0ZM_Xp7KXbWmx3W0Cs:b-208pct) ([raw file](https://github.com/powershell/sqlserverdsc/blob/d5bbb39d7efc1374837bf4874bd4c681e4475796/Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1#L527)):*
> Should Be

New format: `Should -Be`

---

*[Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1, line 533 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-L0ZMgDiybs6fQmKDdDk:-L0ZMgDiybs6fQmKDdDl:b-co19b5) ([raw file](https://github.com/powershell/sqlserverdsc/blob/d5bbb39d7efc1374837bf4874bd4c681e4475796/Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1#L533)):*
> thow

Typo 'throw'.

---

*[Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1, line 545 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-L0ZMbCq6iy0WX04C5mF:-L0ZMbCq6iy0WX04C5mG:b-bswen7) ([raw file](https://github.com/powershell/sqlserverdsc/blob/d5bbb39d7efc1374837bf4874bd4c681e4475796/Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1#L545)):*
> Should Throw

New format: `Should -Throw`

---

*[Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1, line 561 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-L0ZMnoZ16u0LAdx4y6x:-L0ZMnoZ16u0LAdx4y6y:b-bswen7) ([raw file](https://github.com/powershell/sqlserverdsc/blob/d5bbb39d7efc1374837bf4874bd4c681e4475796/Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1#L561)):*
> Should Throw

New format: `Should -Throw`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947)*

**Comment by nabrond** [comment]
Review status: 3 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1, line 413 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-L0YkDgVVOR4uzMgFy4e:-L0a1OCIDgcz9apB6MaE:bhxaqm8) ([raw file](https://github.com/powershell/sqlserverdsc/blob/d5bbb39d7efc1374837bf4874bd4c681e4475796/Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1#L413)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Minor: Maybe add this in a BeforeAll-block, beneath the two context block's below. Then the mock is not available in the third Context-block where "NoServices" are  evaluated.
</blockquote></details>

Not sure if I quite understand what you are looking for here. Is there an order of operations within a `Describe` that would cause the `BeforeAll` to only fire for the first two `Context` entries? Currently, I override the `Mock` in the "NoServices" context.

---

*[Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1, line 465 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-L0ZMQtVQygvkASg7XoV:-L0a0mcy3d6iMYJGb8Lz:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/d5bbb39d7efc1374837bf4874bd4c681e4475796/Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1#L465)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Should Be

New format: `Should -Be`
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1, line 505 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-L0Yl9fmzj8rNnrhXPMs:-L0a1-OJ_h5ag8EyN2XW:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/d5bbb39d7efc1374837bf4874bd4c681e4475796/Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1#L505)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Remove this row since it is commented?
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1, line 509 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-L0YlDO4rkly7eOaJGeD:-L0a1-kJd0EA8RfAl8eJ:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/d5bbb39d7efc1374837bf4874bd4c681e4475796/Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1#L509)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Remove this row since it is commented?
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1, line 527 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-L0ZM_Xp7KXbWmx3W0Cr:-L0a10aiSg0yYKgnPqiL:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/d5bbb39d7efc1374837bf4874bd4c681e4475796/Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1#L527)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Should Be

New format: `Should -Be`
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1, line 533 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-L0ZMgDiybs6fQmKDdDk:-L0a15kooKHs_LOXklnt:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/d5bbb39d7efc1374837bf4874bd4c681e4475796/Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1#L533)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> thow

Typo 'throw'.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1, line 545 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-L0ZMbCq6iy0WX04C5mF:-L0a1FBRts_LdE6uK9Wu:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/d5bbb39d7efc1374837bf4874bd4c681e4475796/Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1#L545)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Should Throw

New format: `Should -Throw`
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1, line 561 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-L0ZMnoZ16u0LAdx4y6x:-L0a1Fh__SuPeiBYytvz:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/d5bbb39d7efc1374837bf4874bd4c681e4475796/Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1#L561)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Should Throw

New format: `Should -Throw`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947)*

**Comment by johlju** [comment]
Changes looks okay! Although something strange happen when you rebased. I no longer see an entry under the Unreleased section. Also, for some reason SqlServerDsc.psd1 is a file that is being "touched" by this PR, when it shouldn't. 
I see commits that shouldn't be in this PR; https://github.com/PowerShell/SqlServerDsc/pull/947/commits. I think the `git rebase` faulted somewhere. :smile: 
Could you see if you can solve it?

---

Reviewed 1 of 1 files at r4.
Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-:-L0hggOw8Od9MUN5swJz:bwaiumw)*

**Comment by nabrond** [comment]
I think my original rebase happened during the v10 release. Ran through another rebase and updated CHANGELOG accordingly by moving my entry up to the `Unreleased` section.

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-:-L0qvT4a7J641QqsatPA:b1sa75p)*

**Comment by johlju** [comment]
:lgtm: 

I will try to resolve the conflicts of the change log thru GitHub. I gave me that option, so gonna try it.

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-:-L0ykn5wrDWb0GJwCJPO:bcah6d9)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/947#-:-L0ylZ4HdT2E5ug_AiQJ:bnfp4nl)*

**Pull request merged**
