### PR TITLE
SqlWaitForAg: Updated unit tests to use latest unit test template

### LINKED ISSUE #1088: SqlWaitForAG: Update unit tests to use the same (newest) unit test template
#### Details of the scenario you tried and the problem that is occurring
The unit tests for this resource is using an old unit test template.
Suggest we update the unit tests to use the latest unit test template.

https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1

#### The DSC configuration that is using the resource (as detailed as possible)
n/a

#### Version of the operating system and PowerShell the target node is running
n/a

#### SQL Server edition and version the target node is running
n/a

#### What SQL Server PowerShell modules, and which version, are present on the target node.
n/a

#### Version of the DSC module you're using, or write 'dev' if you're using current dev branch
Dev

### PR DESCRIPTION
**Pull request by TraGicCode**
#### Pull Request (PR) description
Updated SqlWaitForAg unit tests to used latest unit test template.

#### This Pull Request (PR) fixes the following issues
Fixes #1088 

#### Task list
- [x] Added an entry under the Unreleased section in the CHANGELOG.md? Entry
      should say what was changed, and how that affects users (if applicable).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1100)

### CODE REVIEW

**Comment by johlju** [comment]
Just a small review comment. :)

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[CHANGELOG.md, line 32 at r1](https://beta.reviewable.io/reviews/powershell/sqlserverdsc/1100#-L9AiRVZ1AJbsTpcBc04:-L9AiRVZ1AJbsTpcBc05:bqdoy9f) ([raw file](https://github.com/powershell/sqlserverdsc/blob/b948e8edd7c4c21aa8bad38239cdb68a9ccecc7f/CHANGELOG.md#L32)):*
> ```Markdown
>     the following resources unit test template to version 1.2.1
>     - SqlAlias ([issue #999](https://github.com/PowerShell/SqlServerDsc/issues/999)).
>     - SqlWaitForAG ([issue #1088](https://github.com/PowerShell/SqlServerDsc/issues/1088)).
> ```

Since a new release was made, this is no longer under the Unreleased section. Could you move this new entry to the unreleased section? You can copy the 'Changes to Unit Tests' and 'Updated...' part as well. You can leave out your name for the time being and I will add that back in before next release. :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/sqlserverdsc/1100#-:-L9Aj9uaELptvlle-ght:bbzun0f)*

**Comment by johlju** [comment]
@TraGicCode When you push the change we will see if the tests passes. The failed test has nothing to do with your change, it fails to download the media sometimes which makes the integration tests to fail. :/

**Comment by johlju** [comment]
Just a tiny comment left :smile: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[CHANGELOG.md, line 4 at r2](https://beta.reviewable.io/reviews/powershell/sqlserverdsc/1100#-L9QJ3dc8-k3oLQyhYBG:-L9QJ3dc8-k3oLQyhYBH:b-ao87zp) ([raw file](https://github.com/powershell/sqlserverdsc/blob/7d045b1c728f9d3fd630c26911622d97f364686f/CHANGELOG.md#L4)):*
> ```Markdown
> 
> ## Unreleased
> - Changes to Unit Tests
> ```

Should be a blank line before this one.

Tests are failing on lint error; https://ci.appveyor.com/project/PowerShell/sqlserverdsc/build/9.0.260.0?fullLog=true#L1592

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/sqlserverdsc/1100#-:-L9QJFtT5waJg0fzgTBI:bvc11p6)*

**Comment by TraGicCode** [comment]
Done.

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/sqlserverdsc/1100#-:-L9XyyGp4A62erKmIzls:b-896fix)*

**Comment by TraGicCode** [comment]
*[CHANGELOG.md, line 4 at r2](https://beta.reviewable.io/reviews/powershell/sqlserverdsc/1100#-L9QJ3dc8-k3oLQyhYBG:-L9Xz04wCI9NUdjxZJwh:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/7d045b1c728f9d3fd630c26911622d97f364686f/CHANGELOG.md#L4)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Should be a blank line before this one.

Tests are failing on lint error; https://ci.appveyor.com/project/PowerShell/sqlserverdsc/build/9.0.260.0?fullLog=true#L1592
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/sqlserverdsc/1100)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/sqlserverdsc/1100#-:-L9ZULpL9QMafeESFy8H:bnfp4nl)*

**Comment by johlju** [comment]
@TraGicCode Thanks for that! One more down! 😄

**Pull request merged**
