### PR TITLE
SqlRs: [#864] SSRS 2017 username, service instance names

### LINKED ISSUE #864: SqlRS: Does this resource support Microsoft SQL Server 2017 Reporting Services?
**Details of the scenario you tried and the problem that is occurring:**
In SQL Server 2017 Reporting Services are no longer a part of SQL Server, but a separate install [Microsoft SQL Server 2017 Reporting Services](https://www.microsoft.com/download/details.aspx?id=55252).

Does this, and should this, resource support Microsoft SQL Server 2017 Reporting Services?

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Microsoft SQL Server 2017 Reporting Services

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by bozho**
#### Pull Request (PR) description
SqlRs resource is now aware of SSRS 2017. SSRS 2017 changes the Windows service name, Windows user account name that runs the service, supports a single SSRS instance (named 'SSRS')

#### This Pull Request (PR) fixes the following issues
- partially fixes #864 - it only handles initialisation (i.e. current behaviour), not installing SSRS 2017

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1261)

### CODE REVIEW

**Comment by johlju** [comment]
@bozho Would it possible for you to look at updating the unit tests with the changes here? 🙂

**Comment by bozho** [comment]
Is `codecov/patch` failing a problem? How do I fix it?

**Comment by johlju** [comment]
It looks like rows that previously was hit, is not hit with this change. You need to update MSFT_SqlRs.Tests.ps1 and make sure the tests are testing those rows again.

See red lines here https://codecov.io/gh/PowerShell/SqlServerDsc/pull/1261/src/DSCResources/MSFT_SqlRS/MSFT_SqlRS.psm1

**Comment by johlju** [comment]
This was a better view of the lines not hit, see red lines (left most column) 
https://codecov.io/gh/PowerShell/SqlServerDsc/pull/1261/diff

**Comment by johlju** [comment]
> @johlju Is `codecov/patch` failing a problem? How do I fix it?

It indicates that lines was added that is not tested. So normally this should be all green. It maybe be exceptions, but in this case it's lines that are not tested. 🙂

**Comment by bozho** [comment]
I'll need some help with this... I'm guessing code coverage tracks if code was hit by unit tests, is that correct? If that's the case, I'd need to refactor `MSFT_SqlRS.Tests.ps1` to include test cases for SQL 2017. This seems like a non-trivial task, as the tests currently work with a single SQL version (13)

**Comment by johlju** [comment]
Yes, you need to update the unit tests by adding a new context-block with tests for that version, and maybe update the mocks for the existing tests. Looking at this quickly, i think you need to add mocks for `Test-Path` and `Get-ItemProperty` so the mocks return the correct values depending on what code path should be tested.
 https://github.com/PowerShell/SqlServerDsc/blob/48f99295b5ff9d26adb48455eab85f5261c3c7ad/DSCResources/MSFT_SqlRS/MSFT_SqlRS.psm1#L843

https://github.com/PowerShell/SqlServerDsc/blob/48f99295b5ff9d26adb48455eab85f5261c3c7ad/DSCResources/MSFT_SqlRS/MSFT_SqlRS.psm1#L846

*But it would have been better that the helper function `Get-ReportingServicesData` was tested individually, so that the `Get-ReportingServicesData´ could just be mocked to return the correct values for what is currently is being tested. But no need to do that since it would be more work.*

**Comment by bozho** [comment]
@johlju I haven't forgotten about this, just need to find some time to learn more Pester :) Sorry for the delay.

**Comment by johlju** [comment]
No worries. If you need more help let me know.

**Comment by bozho** [comment]
@johlju How can I run Pester tests locally? I suspect there will be a lot of trial and error here :)

**Comment by bozho** [comment]
Ok, I'm not expert, but several tests are failing here:
```
at <ScriptBlock>, C:\projects\sqlserverdsc\DSCResources\MSFT_SqlRS\MSFT_SqlRS.psm1: line 37
37:     $reportingServicesData = Get-ReportingServicesData -InstanceName $InstanceName
```

The change I've made in `Get-ReportingServicesData` is in the getting the SQL server version:

```
        $sqlVersion = [System.Int32]((Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\$instanceId\Setup" -Name 'Version').Version).Split('.')[0]
```

was changed to:

```
        if( Test-Path -Path "HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\$instanceId\MSSQLServer\CurrentVersion" )
        {
            # SQL Server 2017 SSRS stores current SQL Server version to a different Registry path.
            $sqlVersion = [int]((Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\$InstanceId\MSSQLServer\CurrentVersion" -Name "CurrentVersion").CurrentVersion).Split(".")[0]
        }
        else {
            $sqlVersion = [int]((Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\$instanceId\Setup" -Name "Version").Version).Split(".")[0]
        }
```

My guess is that the error is about `Split` method called on a `$null` value.

I have noticed that in `Unit\MSFT_SqlRs.Tests.ps1`, line 101, mocked `Get-ItemProperty` looks like this:

```
        $mockGetItemProperty = {
            return @{
                InstanceName = $mockInstanceName
                Version      = $mockDynamic_SqlBuildVersion
            }
        }
```

But, I can't find `$mockInstanceName` variable anywhere. There are:
```
        $mockNamedInstanceName = 'INSTANCE'
        $mockDefaultInstanceName = 'MSSQLSERVER'
```
on lines 55 and 56.

It looks like we need to sort out the instance names here, but I think the proper way forward would be to mock different versins of `Get-ReportingServicesData` function, to return data for SQL 2016 and 2017.

**Comment by johlju** [comment]
It seems you found a bug in the tests - the `$mockInstanceName` should probably be `$mockDefaultInstanceName`. Strange that it works though, means that the proper values are not tested maybe. 

I agree that it would be better to split into two tests - one for each version of SQL Server.

You can run the tests locally by running
```
cd <local_repo_folder>
Invoke-Pester .\Tests\Unit\MSFT_SqlRS.Tests.ps1 -CodeCoverage .\DSCResources\MSFT_SqlRS\MSFT_SqlRS.psm1
```

**Comment by johlju** [comment]
> I agree that it would be better to split into two tests - one for each version of SQL Server.

Maybe bad. It should have said, yes I agree that the proper way forward would be to mock different versins of Get-ReportingServicesData, they could be in two different tests (two Context-blocks for example).

**Comment by bozho** [comment]
> It seems you found a bug in the tests - the $mockInstanceName should probably be $mockDefaultInstanceName. Strange that it works though, means that the proper values are not tested maybe.

The current `Get-ReportingServicesData` code on `dev` looks like this (from line 821-ish):
```
    $instanceNamesRegistryKey = 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\Instance Names\RS'

    if ( Get-ItemProperty -Path $instanceNamesRegistryKey -Name $InstanceName -ErrorAction SilentlyContinue )
    {
        $instanceId = (Get-ItemProperty -Path $instanceNamesRegistryKey -Name $InstanceName).$InstanceName
        $sqlVersion = [System.Int32]((Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\$instanceId\Setup" -Name 'Version').Version).Split('.')[0]
```

`$InstanceName` is `$null`, so `$instanceId` will also end up being `$null`. However, the mocked `Get-ItemProperty` doesn't use `-Path`, ignoring the missing `$instanceId` value, simply returning a `Version` string, which is then parsed into `$sqlVersion`

Now, my changes introduce a `Test-Path` for SQL Server 2017's version Registry path `HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\$instanceId\MSSQLServer\CurrentVersion`, which with `$instanceId` being `$null`, resolves to `HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQLServer\CurrentVersion`, which exists even on non-2017 SQL versions. That `Test-Path` returns `$true`, so the next `Get-ItemProperty` goes boom.

**Comment by johlju** [comment]
@bozho To simplify the tests, and because there are more logic inside `Get-ReportingServicesData` after this change, I think we need to create a Describe-block for `Get-ReportingServicesData`, like what is done for `SqlRS\Invoke-RsCimMethod` and test the helper function separately. If this is done we test the logic inside just this helper function. After that, in the tests for the Set-TargetResource function we can just mock the `Get-ReportingServicesData` and make sure it returns the expected values depending on the code path that is tested.

I have some time over this week, if you feel you need help with the above I could look at it this week. Let me know.

**Comment by bozho** [comment]
@johlju I'm very new with Pester and if you could start with the `Describe` block for `Get-ReportingServicesData`, that would be brilliant, thank you! It will definitely speed things up to get this patch in.

I may be a bit slow to reply in the next few days, I've had some unexpected personal stuff I need to deal with, so apologies in advance.

**Comment by johlju** [comment]
@bozho I have added tests for `Get-ReportingServicesData`. Please merge my PR in your fork; https://github.com/bozho/SqlServerDsc/pull/1. When you merge my PR in your fork your branch will automatically update this PR.

After you merge there are only the code changes for this PR that are missing tests for. The lines below does not get hit by any test yet.

```
File            Class Function           Line Command
----            ----- --------           ---- -------
MSFT_SqlRS.psm1       Set-TargetResource  231 if ( [string]::IsNullOrEmpty($ReportServerVirtualDirectory) )...
MSFT_SqlRS.psm1       Set-TargetResource  233 $ReportServerVirtualDirectory = 'ReportServer'
MSFT_SqlRS.psm1       Set-TargetResource  236 if ( [string]::IsNullOrEmpty($ReportsVirtualDirectory) )...
MSFT_SqlRS.psm1       Set-TargetResource  238 $ReportsVirtualDirectory = 'Reports'
MSFT_SqlRS.psm1       Set-TargetResource  241 $reportingServicesServiceName = 'SQLServerReportingServices'
MSFT_SqlRS.psm1       Set-TargetResource  242 $reportingServicesDatabaseName = 'ReportServer'
```

**Comment by johlju** [comment]
@bozho you need to rebase this PR to get in the latest changes.

Also, we should be able to integrate test this resource on RS 2017 now, I just merged a new resource SqlRSSetup that installs the SSRS instance of RS 2017.

So if we change this row

https://github.com/PowerShell/SqlServerDsc/blob/f13c0014c79ad8b848f5cd33bc81daa151810821/Tests/Integration/MSFT_SqlRS.Integration.Tests.ps1#L7

to this

```powershell
if (Test-SkipContinuousIntegrationTask -Type 'Integration' -Category @('Integration_SQL2016','Integration_SQL2017'))
```

Then in the integration tests we need to add this (somewhere appropriate) to switch between the different instance name 'DSCRS2016' and 'SSRS' depending on version of RS.

```powershell
if (Test-ContinuousIntegrationTaskCategory -Category 'Integration_SQL2017')
{
    ....
}
else
{
    ....
}
```

**Comment by johlju** [comment]
@bozho let me know if you need any help with this too. Happy to help if needed. 😃

**Comment by bozho** [comment]
Hi @johlju , thank you so much for the tests, I'll try to add the missing cases.

Regarding integration testing, I see that SSRS instance name is mentioned in `MSFT_SqlRS.config.ps1`, line 30. We could either introduce an SQL version parameter for the config script and build `$ConfigurationData` based on its value. Alternatively, we could change the `InstanceName` value after loading the configuration, but that doesn't seem very nice.

There's also `$ImagePath` option in the `$ConfigurationData` that seems to hold SQL Server iso image path - I'm guessing we need to alter that one, too.

`DSCRS2016` string is also mentioned in integration tests' `README.md` file (line 189)

As a side question: does AppVeyor actually install SQL Server and SSRS? SSRS is a separate download on SQL 2017 - how should we handle that?

**Comment by johlju** [comment]
> As a side question: does AppVeyor actually install SQL Server and SSRS? SSRS is a separate download on SQL 2017 - how should we handle that?

There are two AppVeyor jobs that runs integration tests, with the category names 'Integration_SQL2016' and 'Integration_SQL2017'.

https://github.com/PowerShell/SqlServerDsc/blob/f13c0014c79ad8b848f5cd33bc81daa151810821/appveyor.yml#L14-L22

### The integration tests MSFT_SqlSetup.Integration.Tests.ps1 
installs SQL Server 2016 Database Engine (category name 'Integration_SQL2016'), and the other installs SQL Server 2017 Database Engine (category name 'Integration_SQL2017'). In both cases the installed instance is called DSCSQLTEST. Can also been seen here: https://github.com/PowerShell/SqlServerDsc/tree/dev/Tests/Integration#sqlsetup

### The integration test MSFT_SqlRSSetup.Integration.Tests.ps1 
runs only for the category name 'Integration_SQL2017' and installs the SQL Server 2017 Reporting Services (and the instance name is always 'SSRS'). Can also be seen here https://github.com/PowerShell/SqlServerDsc/tree/dev/Tests/Integration#sqlrssetup

### The integration tests MSFT_SqlRS.Integration.Tests.ps1 
currently only runs for the category name 'Integration_SQL2016'.
 https://github.com/PowerShell/SqlServerDsc/blob/f13c0014c79ad8b848f5cd33bc81daa151810821/Tests/Integration/MSFT_SqlRS.Integration.Tests.ps1#L7-L10

It installs the SQL Server 2016 Reporting Services (SqlSetup) as a prerequisites with an instance name of 'DSCRS2016', and after that runs the integration tests for SqlRS resource. SqlRs is run on the instance 'DSCRS2016' but used the instance 'DSCSQLTEST' as the database instance (that instance was installed during the integration tests of SqlSetup above).

**Comment by johlju** [comment]
So I think to support integration tests for the SSRS instance that was installed by the integration test MSFT_SqlRSSetup.Integration.Tests.ps1 we need to make sure that the SqlRs integration tests run for the category 'Integration_SQL2017' too, like this.

```
if (Test-SkipContinuousIntegrationTask -Type 'Integration' -Category @('Integration_SQL2016','Integration_SQL2017'))
{
    return
}
```

And then for the 'Integration_SQL2017' category we need to switch out the 'DSCRS2016' instance name with 'SSRS'.

After this:

https://github.com/PowerShell/SqlServerDsc/blob/f13c0014c79ad8b848f5cd33bc81daa151810821/Tests/Integration/MSFT_SqlRS.Integration.Tests.ps1#L35-L36

Add this (for example):
```
if (Test-ContinuousIntegrationTaskCategory -Category 'Integration_SQL2017')
{
    # $ConfigurationData was dot-source above.
    $ConfigurationData.AllNodes.InstanceName = 'SSRS'
}
```

**Comment by bozho** [comment]
@johlju Thank you for the guidance, I'll have a look through the integration tests code some more to get a better understanding.

**Comment by johlju** [comment]
@bozho Sounds good! LEt me know if you have any more questions, or if you need any help.

**Comment by bozho** [comment]
Hi @johlju,

I'm having some problems with integration testing... I've tried to isolate SSRS 2016 install part in `MSFT_SqlRS.Integration.Tests.ps1` when running 2017 integration tests.

Currently, `[[SqlRS][Integration_Test]` resource is failing when trying to configure SSRS with a message: 
```
PowerShell DSC resource MSFT_SqlRS  failed to execute Set-TargetResource functionality with error message: Method GenerateDatabaseCreationScript() failed with an error. Error:  (HRESULT:-2147023181)
```

Does the new `SqlRSSetup` resource configure the SSRS 2017 instance, too?

**Comment by johlju** [comment]
@bozho Sorry for not responding earlier. No the SqlRSSetup does not configure the Reporting Services instance, but there can be two problems here. 

1. The Reporting Services instance 'SSRS' is stopped by the integration test SqlRSSetup, which mean you need to start the service first. See https://github.com/PowerShell/SqlServerDsc/tree/dev/Tests/Integration#sqlrssetup
2. The Reporting Services instance 'SSRS' is installed on the AppVeyor build worker prior to the integration tests for SqlRSSetup is run. That means the SqlRSSetup is just upgrading the instance, but does not configure the instance. Although, since it is already installed, maybe it is configured already, and that is the problem? I was expecting it to just be installed.

You can debug the build worker if you need to https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

If you see that there is a problem with doing an integration tests that cannot be solved, let me know.

**Comment by johlju** [comment]
@bozho The SSRS instance is stopped using this configuration, so in the integraiton tests for SqlRS for SQL 2017 it should start the instance instead where it installs the SQL 2016 RS for the SQL 2016 tests. Does that make sense?

https://github.com/PowerShell/SqlServerDsc/blob/dfd32b3ca3a364996a2dd9908f77dfb4f7f5f507/Tests/Integration/MSFT_SqlRSSetup.config.ps1#L73-L90

I'm hoping that the SSRS instance is not configured. I realize that can give problems that might not be able to be solved?

**Comment by bozho** [comment]
@johlju Ok, found the next problem: `Restart-ReportingServicesService` helper function is not version-aware, so it always builds an old-style instance name string if `$SQLInstanceName` parameter is not `MSSQLSERVER`. Need to think about the best way to fix that.

**Comment by johlju** [comment]
Maybe just add optional parameter `ServiceName`, and if it is not set, then it builds the service name as today. If it is set then just use the provided service name for the service and dependent service restart? :thinking:

**Comment by bozho** [comment]
@johlju Ok, I've changed `Restart-ReportingServicesService` to first look for SSRS 2017 if `$SQLInstanceName` is `SSRS`, then for pre-2017 named instances. I feel that is good enough.

As you can see from the following commits, that opened up a host of new problems that I'm making my way through.

The last AppVeyor integration test results got me confused, though. For the 2017 scenario, `[[SqlRS]Integration_Test]` test for `MSFT_SqlRS_InstallReportingServices_Config` passes (both `Start-DscConfiguration` and `Get-DscConfiguration` calls), but for `MSFT_SqlRS_InstallReportingServices_ConfigureSsl_Config`, only `Start-DscConfiguration` passes, while `Get-DscConfiguration` fails (you can see it in the log), while calling `Get-TargetResource`, which was apparently successfully executed from the `Test` step of `Start-DscConfiguration` call.

Another curious test result is here, for line 334, where we get a 401 instead of 200:
https://github.com/bozho/SqlServerDsc/blob/7a172f87f1cc97e4c2f62d6f9e036f40a9d8c8d7/Tests/Integration/MSFT_SqlRS.Integration.Tests.ps1#L318-L334

However, when I RDP into the AppVeyor instance and run the web request from that test, it returns the expected 200..

I've enabled AppVeyor RDP, you can find the password in the `appveyor.yml` file, if you want to give it a go yourself...

**Comment by johlju** [comment]
>Another curious test result is here, for line 334, where we get a 401 instead of 200:

The http status code 401 means unauthorized, and since that test are using `-UseDefaultCredentials` I guess the local account  'appveyor' need to have permission to access the ReportingService site, or we need to call the website with an account that do have permission?
If you RDP into the appveyor build worker, can you access the site then with any account, or is the site "dead" because a configuration is missing? I usually add this line somewhere in the test to halt the execution if i want to test something while the tests are running. This line halts the execution until a file on the desktop is deleted.

```
$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
```

**Comment by johlju** [comment]
Btw. The appveyor build worker is only available for 60 minutes (300 minutes on the PowerShell account), after that the build worker need to be re-run. I usually branch out to a 'debug-mybranch' and run these tests on my own fork (the repo in my fork is connected to my free AppVeyor account). Then I can just re-run a commit easily.

**Comment by johlju** [comment]
>The last AppVeyor integration test results got me confused, though. For the 2017 scenario, `[[SqlRS]Integration_Test]` test for `MSFT_SqlRS_InstallReportingServices_Config` passes (both `Start-DscConfiguration` and `Get-DscConfiguration` calls), but for `MSFT_SqlRS_InstallReportingServices_ConfigureSsl_Config`, only `Start-DscConfiguration` passes, while `Get-DscConfiguration` fails (you can see it in the log), while calling `Get-TargetResource`, which was apparently successfully executed from the `Test` step of `Start-DscConfiguration` call.

I agree, this is very strange. Maybe use the method of halting the test mentioned in previous comment so you can run the Get-DscConfiguration manually.

As a side not, if you branch out to a 'debug-mybranch' then you can remove other non-relevant tests (unit and integration tests). I usually remove DSC resource not needed, all examples, all unit an integration tests that the test I'm debugging is not dependent on. That way I speed up each test run. But I do that in a seperate branch so I don't mess up the working branch. :smile:

**Comment by bozho** [comment]
Ok, I tried running just the 2017 integration tests on a separate branch. I've commented out `Meta`, `Unit` and 2016 integration tests in `appveyor.yml` and that didn't run any tests.

I've uncommented `Meta` tests and both `Meta` and 2017 integration tests passed - all 206 integration tests passed. This is confusing.

I'm running `Meta` and both 2016 and 2017 tests now.

**Comment by bozho** [comment]
@johlju When I run `Meta`, 2016 and 2017 integration tests, one test fails on 2017 integration test:
```
Expected exactly 200, but got 401.

at <ScriptBlock>, C:\projects\sqlserverdsc\Tests\Integration\MSFT_SqlRS.Integration.Tests.ps1: line 334
334:                 $webRequestStatusCode | Should -BeExactly 200
```

When I RDP in as the `appveyor` user and run the same request, I get a `200`

The other two tests that failed here seem to have passed. This feels very stochastic :-)

**Comment by johlju** [comment]
@bozho Maybe the test tries to fast? Maybe we should give it time to start up. Maybe we should pause `Start-Sleep-Seconds 10` for the service to start the web site? Could you try to add `Start-Sleep-Seconds 60` (wait a minute) just to see if the error disappears? Then we could lower the value to something more realistic.
The build worker isn't that quick either. Is running on limited resources, so that can be one reason we are seeing these random errors. Sleeping a give it time to start would help. 
Although we should try to minimize how long it sleeps. Less sleep time, more time for other tests. :)

**Comment by bozho** [comment]
@johlju I'm on fire today! :-)

It looks like the reason for the 401 was that the tests are altering SSL configuration for SSRS. The tests switch SSL on and then back off, and then with the SSL just turned off, the test attempts to connect and gets a 401. 

By the time I RDP in, the SSRS service has been stopped by the test, so I have to (re)start it, and the connection works fine.

It seems that we need to restart SSRS whenever we alter SSRS configuration - this is in line with the issue #1331 I created today, where the web portal returns 503 after changing reserved URLs until SSRS service is restarted.

**Comment by bozho** [comment]
Yup, all the tests just passed fine on my debug branch

**Comment by johlju** [comment]
Awesome detective work! Will you send in the restart issue on a separate PR or do you work it in here?

**Comment by bozho** [comment]
I can do the restart on #1331, rebase this branch onto that one - it might be cleaner to separate work.

**Comment by bozho** [comment]
@johlju I'm away next week, we'll sort out any outstanding issues the week after.

**Comment by johlju** [comment]
@bozho I merged the other PR.

**Comment by johlju** [comment]
@bozho is this one ready for review again? :)

**Comment by bozho** [comment]
@johlju Yup.

**Comment by johlju** [comment]
I will revis this later today. Sorry it taken so long! 😞

**Comment by johlju** [comment]
The comment about `Get-SqlInstanceMajorVersion`, I'm happy if you just want to create an issue to track that.  🙂

**Comment by johlju** [comment]
Closing and reopening to kick off the tests again.

**Comment by johlju** [comment]
@bozho Thank you for this! Great work on this one!

**Pull request merged**
