### PR TITLE
SqlServerDsc: Adding note to obsolete examples

### LINKED ISSUE #904: Example references bad resource names
https://github.com/mgreenegit/SqlServerDsc/blob/dev/Examples/SQL-ClusterDB.ps1

xSQLServerFailoverClusterSetup is not a valid resource name

### PR DESCRIPTION
**Pull request by johlju**
**Pull Request (PR) description**
- Changes to SqlServerDsc
  - The examples in the root of the Examples folder are obsolete. Those examples
    now have a note saying so, in the comment-based help, until they can be replaced (issue #904).

**This Pull Request (PR) fixes the following issues:**
Fixes #904 

**Task list:**

- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/920)

### CODE REVIEW

**Comment by johlju** [comment]
@randomnote1 Do you mind reviewing this one? My English grammar isn't the best. :)

**Comment by randomnote1** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 13 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/920#-L-7yfW3wovm3mHtMNXR:-L-7yfW3wovm3mHtMNXS:baht9ii) ([raw file](https://github.com/powershell/sqlserverdsc/blob/6081158b75101df318fd5234f6caa2cad50dba85/CHANGELOG.md#L13)):*
> Those examples
>     now have a note saying so, in the comment-based help, until they can be replaced

Maybe something like this?

`A note was added to the comment-based help in each example stating it is obsolete. This is a temporary measure until they are replaced.`

---

*[Examples/DSCClusterSqlBuild.ps1, line 4 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/920#-L-7zQ6xpg0yvLEdNUpw:-L-7zQ6xpg0yvLEdNUpx:bvdzzz4) ([raw file](https://github.com/powershell/sqlserverdsc/blob/6081158b75101df318fd5234f6caa2cad50dba85/Examples/DSCClusterSqlBuild.ps1#L4)):*
> THIS EXAMPLE IS OBSOLETE. Due to major changes to the resource modules
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>         (this and other modules) over the last few months this example has not
>         been updated to reflect those changes.
>         Please refer to the examples in each individual resource example folder
>         for updated examples.
>         https://github.com/PowerShell/SqlServerDsc/tree/dev/Examples/Resources
</details>
>  
>         There is an issue open to replace this example, please see issue
>         https://github.com/PowerShell/SqlServerDsc/issues/462

Try this here and throughout.

```
THIS EXAMPLE IS OBSOLETE. Due to major changes in the resource modules 
over the last several versions, this example has not been updated to reflect
those changes.
Please refer to the resource example folder for updated examples.
https://github.com/PowerShell/SqlServerDsc/tree/master/Examples/Resources

There is an issue open to replace this example, please see issue
https://github.com/PowerShell/SqlServerDsc/issues/462
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/920)*

**Comment by randomnote1** [comment]
@johlju, I added some comments that apply to all of the changes. When they're updated, they should be good to go.

**Comment by johlju** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 13 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/920#-L-7yfW3wovm3mHtMNXR:-L-C_rnEywFyZUZH5YW2:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/6081158b75101df318fd5234f6caa2cad50dba85/CHANGELOG.md#L13)):*
<details><summary><i>Previously, randomnote1 (Dan Reist) wrote…</i></summary><blockquote>

> Those examples
>     now have a note saying so, in the comment-based help, until they can be replaced

Maybe something like this?

`A note was added to the comment-based help in each example stating it is obsolete. This is a temporary measure until they are replaced.`
</blockquote></details>

Done.

---

*[Examples/DSCClusterSqlBuild.ps1, line 4 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/920#-L-7zQ6xpg0yvLEdNUpw:-L-C_sSd1uZP2gPmuxHb:b-v16ojf) ([raw file](https://github.com/powershell/sqlserverdsc/blob/6081158b75101df318fd5234f6caa2cad50dba85/Examples/DSCClusterSqlBuild.ps1#L4)):*
<details><summary><i>Previously, randomnote1 (Dan Reist) wrote…</i></summary><blockquote>

> THIS EXAMPLE IS OBSOLETE. Due to major changes to the resource modules
>         (this and other modules) over the last few months this example has not
>         been updated to reflect those changes.
>         Please refer to the examples in each individual resource example folder
>         for updated examples.
>         https://github.com/PowerShell/SqlServerDsc/tree/dev/Examples/Resources
>  
>         There is an issue open to replace this example, please see issue
>         https://github.com/PowerShell/SqlServerDsc/issues/462

Try this here and throughout.

```
THIS EXAMPLE IS OBSOLETE. Due to major changes in the resource modules 
over the last several versions, this example has not been updated to reflect
those changes.
Please refer to the resource example folder for updated examples.
https://github.com/PowerShell/SqlServerDsc/tree/master/Examples/Resources

There is an issue open to replace this example, please see issue
https://github.com/PowerShell/SqlServerDsc/issues/462
```
</blockquote></details>

Done. Thanks for the much improved text! :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/920)*

**Comment by johlju** [comment]
@randomnote1 if you have time, can you sign off on the changes?

**Comment by randomnote1** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/920#-:-L-CdAHomYMyQ_7B4KIr:bnfp4nl)*

**Comment by johlju** [comment]
@randomnote1 Big thanks for reviewing!

**Pull request merged**
