### PR TITLE
Adds New Resource SqlScriptQuery

### LINKED ISSUE #719: SqlScript: Store queries in configuration properties
**Details of the scenario you tried and the problem that is occurring:**
I believe xSQLServerScript should behave in a manner consistent with the [DSC Script resource](https://docs.microsoft.com/en-us/powershell/dsc/scriptResource) where the contents of the Get/Set/Test scripts are stored in the configuration, not in an external file. I do see the value in being able to execute the Get/Set/Test from external SQL files, so I believe that functionality should be retained.

I propose the following properties be added to the resource:
- GetScript
- SetScript
- TestScript

This will be consistent with the DSC Script resource. The logic of the resource should be updated to allow any combination of the Get*, Set*, and Test* properties (eg. GetScript, TestScript, SetFilePath), but throw an error if both Get*, Set*, or Test* properties are set. This would be easiest with parameter sets, however that functionality is not available yet.

**The DSC configuration that is using the resource (as detailed as possible):**
```
Configuration ExampleSqlScript
{
    param
    (
        [Parameter(Mandatory = $true)]
        [PSCredential]
        $WindowsCredential,

        [Parameter(Mandatory = $false)]
        [System.String]
        $SaName = 'RenamedSa'
    )
    
    xSQLServerScript 'ChangeSaName'
    {
        ServerInstance = 'localhost\SQL2016'
        GetScript = 'SELECT Name FROM sys.server_principals WHERE principal_id = 1'
        SetScript = "
            DECLARE @saName sysname
            DECLARE @alterUser varchar(max)

            SELECT @saName = Name
            FROM sys.server_principals
            WHERE principal_id = 1

            SET @alterUser = 'ALTER LOGIN [' + @saName + '] WITH Name = [$SaName]'

            EXEC sp_executesql @alterUser
        "
        TestScript = "
            SELECT
                CASE
                    WHEN Name = '$SaName' THEN 1 
                    ELSE 0 
                END 
            FROM sys.server_principals
            WHERE principal_id = 1
        "
        PsDscRunAsCredential = $WindowsCredential
    }
}
```

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
N/A

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
N/A

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
v8.0.0.0/dev

### PR DESCRIPTION
**Pull request by chasewilson**
#### Pull Request (PR) description
Adds the ability to use Strings as queries for the SqlScript resource instead of just file paths to sql scripts

#### This Pull Request (PR) fixes the following issues
Fixes #719

#### Task list

- [x] Added an entry under the Unreleased section in the CHANGELOG.md? Entry
      should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md?
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help?
- [x] Comment-based help added/updated?
- [x] Localization strings added/updated in all localization files as appropriate?
- [x] Examples appropriately added/updated?
- [x] Unit tests added/updated?
      See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible)?
      See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to
      [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)
      and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md)?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1126)

### CODE REVIEW

**Comment by johlju** [comment]
@chasewilson Awesome work! I will review this later today.

**Comment by johlju** [comment]
This looks really great now! Just a few minor review comments, then I think this is good to go! Thanks for hanging in there and making a new PR an all that :smiley:  :bowing_man: 

---

Reviewed 14 of 18 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[CHANGELOG.md, line 8 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCDtKbK97QpXxDQowYm:-LCDtKbK97QpXxDQowYn:b8v5koh) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/CHANGELOG.md#L8)):*
> ```Markdown
>   - Moved decoration for integration test to resolve a breaking change in
>     DscResource.Tests.
>   - [Chase Wilson(@chasewilson)](https://github.com/chasewilson):
> ```

In another repo we discussed having the names at the end instead, to be less intrusive on those reading the change log (i changed this for the latest release).
So could we maybe do this? 

```
  - New resources:
    - Added SqlScriptQueryResource. [Chase Wilson(@chasewilson)](https://github.com/chasewilson)
```

---

*[DSCResources/MSFT_SqlScript/MSFT_SqlScript.psm1, line 172 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCDx3a7-msuDRsQUCwS:-LCDx3a7-msuDRsQUCwT:b5ic29z) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/DSCResources/MSFT_SqlScript/MSFT_SqlScript.psm1#L172)):*
> ```PowerShell
>         $Variable
>     )
>     $invokeParameters = @{
> ```

Can we add a blank row before this one?

---

*[Tests/Integration/MSFT_SqlScript.config.ps1, line 1 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCDvCcp1CDXthtKVic8:-LCDvCcp1CDXthtKVic9:b-3lf4ij) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/Tests/Integration/MSFT_SqlScript.config.ps1#L1)):*
> ```PowerShell
> <#
> ```

Line 1-9 can be removed here. This is only needed in the *.Integration.Tests.ps1 file and it's already present there. So just remove line 1-9 here.

---

*[Tests/Integration/MSFT_SqlScript.config.ps1, line 67 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCE0PJt5nShi4_N018m:-LCE0PJt5nShi4_N018n:b-ww4ltp) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/Tests/Integration/MSFT_SqlScript.config.ps1#L67)):*
> ```PowerShell
>     Import-DscResource -ModuleName 'SqlServerDsc'
> 
>     node localhost {
> ```

Not part of your change. But would you mind moving the braces to the next row here? :slightly_smiling_face: 

---

*[Tests/Integration/MSFT_SqlScript.config.ps1, line 198 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCE0WxA8vfCg6nzg15R:-LCE0WxA8vfCg6nzg15S:b-ww4ltp) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/Tests/Integration/MSFT_SqlScript.config.ps1#L198)):*
> ```PowerShell
>     Import-DscResource -ModuleName 'SqlServerDsc'
> 
>     node localhost {
> ```

Not part of your change. But would you mind moving the braces to the next row here? :slightly_smiling_face: 

---

*[Tests/Integration/MSFT_SqlScript.config.ps1, line 228 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCE0YFbC3Qw5bliPo6X:-LCE0YFbC3Qw5bliPo6Y:b-ww4ltp) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/Tests/Integration/MSFT_SqlScript.config.ps1#L228)):*
> ```PowerShell
>     Import-DscResource -ModuleName 'SqlServerDsc'
> 
>     node localhost {
> ```

Not part of your change. But would you mind moving the braces to the next row here? :slightly_smiling_face: 

---

*[Tests/Integration/MSFT_SqlScriptQuery.config.ps1, line 1 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCDvMOe3cFF2eZ06E_J:-LCDvMOe3cFF2eZ06E_K:b-3lf4ij) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/Tests/Integration/MSFT_SqlScriptQuery.config.ps1#L1)):*
> ```PowerShell
> <#
> ```

Line 1-9 can be removed here. This is only needed in the *.Integration.Tests.ps1 file and it's already present there. So just remove line 1-9 here.

---

*[Tests/Integration/MSFT_SqlScriptQuery.config.ps1, line 61 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCE0aml2SD6ntUAVn8M:-LCE0aml2SD6ntUAVn8N:ba0555d) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/Tests/Integration/MSFT_SqlScriptQuery.config.ps1#L61)):*
> ```PowerShell
>     Import-DscResource -ModuleName 'SqlServerDsc'
> 
>     node localhost {
> ```

Can we move the braces to the next row here?

---

*[Tests/Integration/MSFT_SqlScriptQuery.config.ps1, line 62 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCE0cbv92J5I0Je7tl_:-LCE0cbv92J5I0Je7tla:bp5cpe) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/Tests/Integration/MSFT_SqlScriptQuery.config.ps1#L62)):*
> ```PowerShell
> 
>     node localhost {
> ```

We could remove this blank row.

---

*[Tests/Integration/MSFT_SqlScriptQuery.config.ps1, line 110 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCE0fCNE9K7wPLVRkXY:-LCE0fCNE9K7wPLVRkXZ:ba0555d) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/Tests/Integration/MSFT_SqlScriptQuery.config.ps1#L110)):*
> ```PowerShell
>     Import-DscResource -ModuleName 'SqlServerDsc'
> 
>     node localhost {
> ```

Can we move the braces to the next row here?

---

*[Tests/Integration/MSFT_SqlScriptQuery.config.ps1, line 140 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCE0jrX3KaeHqsk5rGQ:-LCE0jrX3KaeHqsk5rGR:ba0555d) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/Tests/Integration/MSFT_SqlScriptQuery.config.ps1#L140)):*
> ```PowerShell
>     Import-DscResource -ModuleName 'SqlServerDsc'
> 
>     node localhost {
> ```

Can we move the braces to the next row here?

---

*[Tests/Unit/SqlServerDSCHelper.Tests.ps1, line 1874 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCE1D-E4Pi1aZlDjvRE:-LCE1D-E4Pi1aZlDjvRF:b-6ur3b9) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/Tests/Unit/SqlServerDSCHelper.Tests.ps1#L1874)):*
> ```PowerShell
> 
>     Describe "Invoke-SqlScript" {
> ```

We can remove this extra blank line.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-:-LCE1_6n28f2ykIbYEfh:bgca9zg)*

**Comment by chasewilson** [comment]
Took me long enough :) Thank YOU for hanging in there it has been a really good learning experience for me, so thank you

---

Review status: 13 of 18 files reviewed at latest revision, 12 unresolved discussions.

---

*[CHANGELOG.md, line 8 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCDtKbK97QpXxDQowYm:-LCEieWT3OiMEmwzPgpU:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/CHANGELOG.md#L8)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

In another repo we discussed having the names at the end instead, to be less intrusive on those reading the change log (i changed this for the latest release).
So could we maybe do this? 

```
  - New resources:
    - Added SqlScriptQueryResource. [Chase Wilson(@chasewilson)](https://github.com/chasewilson)
```
</blockquote></details>

Done.

---

*[DSCResources/MSFT_SqlScript/MSFT_SqlScript.psm1, line 172 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCDx3a7-msuDRsQUCwS:-LCEj5U_8b94B1mF0ugQ:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/DSCResources/MSFT_SqlScript/MSFT_SqlScript.psm1#L172)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Can we add a blank row before this one?
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_SqlScript.config.ps1, line 1 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCDvCcp1CDXthtKVic8:-LCEjUeZEZ9m-Li6FXAT:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/Tests/Integration/MSFT_SqlScript.config.ps1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Line 1-9 can be removed here. This is only needed in the *.Integration.Tests.ps1 file and it's already present there. So just remove line 1-9 here.
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_SqlScript.config.ps1, line 67 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCE0PJt5nShi4_N018m:-LCElDnO7TNFTfBmtwrK:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/Tests/Integration/MSFT_SqlScript.config.ps1#L67)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Not part of your change. But would you mind moving the braces to the next row here? :slightly_smiling_face: 
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_SqlScript.config.ps1, line 198 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCE0WxA8vfCg6nzg15R:-LCElEPo6JCwtdnp0RVV:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/Tests/Integration/MSFT_SqlScript.config.ps1#L198)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Not part of your change. But would you mind moving the braces to the next row here? :slightly_smiling_face: 
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_SqlScript.config.ps1, line 228 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCE0YFbC3Qw5bliPo6X:-LCElEti8fdMmrQi7wCR:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/Tests/Integration/MSFT_SqlScript.config.ps1#L228)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Not part of your change. But would you mind moving the braces to the next row here? :slightly_smiling_face: 
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_SqlScriptQuery.config.ps1, line 1 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCDvMOe3cFF2eZ06E_J:-LCElHiID_TeK7nwue6r:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/Tests/Integration/MSFT_SqlScriptQuery.config.ps1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Line 1-9 can be removed here. This is only needed in the *.Integration.Tests.ps1 file and it's already present there. So just remove line 1-9 here.
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_SqlScriptQuery.config.ps1, line 61 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCE0aml2SD6ntUAVn8M:-LCElIB66e1_PQ61JOWb:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/Tests/Integration/MSFT_SqlScriptQuery.config.ps1#L61)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Can we move the braces to the next row here?
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_SqlScriptQuery.config.ps1, line 62 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCE0cbv92J5I0Je7tl_:-LCElI__A9VVMdwHoVFM:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/Tests/Integration/MSFT_SqlScriptQuery.config.ps1#L62)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We could remove this blank row.
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_SqlScriptQuery.config.ps1, line 110 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCE0fCNE9K7wPLVRkXY:-LCElM5JBoRlgbbzyruK:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/Tests/Integration/MSFT_SqlScriptQuery.config.ps1#L110)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Can we move the braces to the next row here?
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_SqlScriptQuery.config.ps1, line 140 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCE0jrX3KaeHqsk5rGQ:-LCElMuE3waq6h_U4iQR:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/Tests/Integration/MSFT_SqlScriptQuery.config.ps1#L140)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Can we move the braces to the next row here?
</blockquote></details>

Done.

---

*[Tests/Unit/SqlServerDSCHelper.Tests.ps1, line 1874 at r2](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-LCE1D-E4Pi1aZlDjvRE:-LCEmP876J3yFNs3ylGa:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/ba599fdbdf240e561a54261dcf4e0d656ffc3319/Tests/Unit/SqlServerDSCHelper.Tests.ps1#L1874)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can remove this extra blank line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-:-LCEmYMV8smk6xW-0CeE:bbtplne)*

**Comment by johlju** [comment]
You are welcome! Always happy to help! :slightly_smiling_face: 

This looks good - I just have to check the tests since they are failing on something that is not part of this PR.

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1126#-:-LCTyUF07hgiyEZxmGKk:bif82uo)*

**Comment by johlju** [comment]
Closing and reopening this PR to kick off the tests again, since it fails on the loopback adapter in the integration tests.

**Pull request merged**
