### PR TITLE
SqlSetup: MSFT_SqlSetup.psm1 enable Robocopy to use paths containing spaces

### LINKED ISSUE #779: SqlSetup: fails if there are spaces in SourcePath
I suspect the offending line is here where the robocopy argument list is constructed without quotes:

https://github.com/PowerShell/xSQLServer/blob/4734f6657ce8ad90b0d216a7cbc7ca8325dc8bba/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L1889

Somehow in my case this actually caused xSQLServerSetup to confusingly report that robocopy determined that all the files were already present.

### PR DESCRIPTION
**Pull request by prkelly**
Enabling Robocopy to use paths containing spaces (https://github.com/PowerShell/SqlServerDsc/issues/779)

#### Pull Request (PR) description
    SqlSetup: MSFT_SqlSetup.psm1 enable Robocopy to use paths containing spaces

#### This Pull Request (PR) fixes the following issues
Fixes #779 

#### Task list

- [x] Added an entry under the Unreleased section in the CHANGELOG.md? Entry
      should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md?
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help?
- [ ] Comment-based help added/updated?
- [ ] Localization strings added/updated in all localization files as appropriate?
- [ ] Examples appropriately added/updated?
- [x] Unit tests added/updated?
      See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible)?
      See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x ] New/changed code adheres to
      [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)
      and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md)?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1131)

### CODE REVIEW

**Comment by johlju** [comment]
Thanks for fixing this! 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/powershell/sqlserverdsc/1131#-LE9qXtE0P_IkHOzFe1d:-LE9qXtE0P_IkHOzFe1e:b-srdyx) (no related file):*
Please look at the failing tests (see other review comment as well); https://ci.appveyor.com/project/PowerShell/sqlserverdsc/build/9.0.318.0?fullLog=true#L692

---

*[a discussion](https://reviewable.io/reviews/powershell/sqlserverdsc/1131#-LE9rMqY0O6Otsfttzdm:-LE9rMqY0O6Otsfttzdn:b-6bt7c2) (no related file):*
Could you please add an descriptive entry, for each change/issue, to the Unreleased section of the change log in the file README.md? If an entry resolves an issue please reference the issue where applicable. You may suffix (it's optional) each entry with your name. Example of the format for the entry.
```
* Descriptive entry ([issue #123](https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/123). [Name/Alias (@github_account)](https://github.com/github_account)
```

---

*[DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1, line 1929 at r1](https://reviewable.io/reviews/powershell/sqlserverdsc/1131#-LE9q_nXCHZrSdjF4IJq:-LE9q_nXCHZrSdjF4IJr:b7rc2cg) ([raw file](https://github.com/powershell/sqlserverdsc/blob/93439d1d523cf7fe26420ec4a5b8dbf6b746654a/DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1#L1929)):*
> ```PowerShell
>         [System.String]
>         $DestinationPath
>     }
> ```

I think this was mistakenly changed to a `}` instead of a `)`.

---

*[DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1, line 1930 at r1](https://reviewable.io/reviews/powershell/sqlserverdsc/1131#-LE9qiJbBxlzbg_NBCJX:-LE9qiJbBxlzbg_NBCJY:b4cikjj) ([raw file](https://github.com/powershell/sqlserverdsc/blob/93439d1d523cf7fe26420ec4a5b8dbf6b746654a/DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1#L1930)):*
> ```PowerShell
>         $DestinationPath
>     }
>     $quotedPath = '"{0}"' -f $Path
> ```

Please add a unit test that test this function using spaces in the paths so we can test this change; See other unit tests for this helper function https://github.com/PowerShell/SqlServerDsc/blob/dev/Tests/Unit/MSFT_SqlSetup.Tests.ps1#L4522

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1131#-:-LE9rAC7BhWtFktGWFhj:b-d05gmx)*

**Comment by johlju** [comment]
When you have resolved the review comments, or if you need to discuss a comment. Could you please go into Reviewable and write 'Done' (or click the done-button) on each of the review comments. This allows me to acknowledge (resolve) the review comments and I know that you are done with each change. After you written 'Done' on each review comment,  or comment on the review comment if it needs further discussion, then click the big green 'Publish' button on top of the page. That will send all your comments back as one big comment to this PR.
You find Reviewable if you click on the big purple Reviewable-button in the PR description.

**Comment by prkelly** [comment]
thanks for the feedback johlju; have fixed the failing tests and updated Changelog etc. just submitted unit tests for this change (am not able to access Reviewable for some reason - returns message "no connection to firebase - 1 pending write (1stalled) - waiting on permission checks")

**Comment by johlju** [comment]
@prkelly Try Reviewable again in a bit - GitHub had trouble yesterday and I got that too then.

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1131#-:-LEsZi2aDd-122_mUl27:bnfp4nl)*

**Pull request merged**
