### PR TITLE
SqlSetup: Fix for issue 448

### LINKED ISSUE #448: SqlSetup: Unable to enable debug mode
When I tried to enable debug mode for DSC by using: 
 Enable-DscDebug -BreakAll

Then when I run 

Start-DscConfiguration -Path .\SQLServerSetup -Wait -Verbose -Force

Instead of entering breaking mode, it returns error:

Start-DscConfiguration -Path .\SQLServerSetup -Wait -Verbose -Force
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' =
 MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SQL2016 with user sid S-1-5-21-2704606996-4249334842-1457779825-500.
VERBOSE: [SQL2016]: LCM:  [ Start  Set      ]
WARNING: [SQL2016]:                            [DSCEngine] Warning LCM is in Debug 'ResourceScriptBreakAll' mode.  Resource s
cript processing will be stopped to wait for PowerShell script debugger to attach.
VERBOSE: [SQL2016]:                            [DSCEngine] Importing the module C:\Windows\system32\WindowsPowerShell\v1.0\Mo
dules\xSqlServer\5.0.0.0\DscResources\MSFT_xSQLServerSetup\MSFT_xSQLServerSetup.psm1 in force mode.
VERBOSE: [SQL2016]:                            [DSCEngine] Importing the module C:\Windows\system32\WindowsPowerShell\v1.0\Mo
dules\xSqlServer\5.0.0.0\DscResources\MSFT_xSQLServerFirewall\MSFT_xSQLServerFirewall.psm1 in force mode.
VERBOSE: [SQL2016]:                            [DSCEngine] Importing the module C:\Windows\system32\WindowsPowerShell\v1.0\Mo
dules\xSqlServer\5.0.0.0\DscResources\MSFT_xSQLServerMemory\MSFT_xSQLServerMemory.psm1 in force mode.
VERBOSE: [SQL2016]:                            [DSCEngine] Importing the module C:\Windows\system32\WindowsPowerShell\v1.0\Mo
dules\xSqlServer\5.0.0.0\DscResources\MSFT_xSQLServerConfiguration\MSFT_xSQLServerConfiguration.psm1 in force mode.
VERBOSE: [SQL2016]:                            [DSCEngine] Importing the module C:\Windows\system32\WindowsPowerShell\v1.0\Mo
dules\xSqlServer\5.0.0.0\DscResources\MSFT_xSQLServerMaxDop\MSFT_xSQLServerMaxDop.psm1 in force mode.
VERBOSE: [SQL2016]: LCM:  [ Start  Resource ]  [[xSQLServerSetup]localhost]
VERBOSE: [SQL2016]: LCM:  [ Start  Test     ]  [[xSQLServerSetup]localhost]
VERBOSE: [SQL2016]:                            [[xSQLServerSetup]localhost] Importing the module MSFT_xSQLServerSetup in forc
e mode.
WARNING: [SQL2016]:                            [[xSQLServerSetup]localhost] Resource is waiting for PowerShell script debugge
r to attach.  Use the following commands to begin debugging this resource script:
Enter-PSSession -ComputerName SQL2016 -Credential <credentials>
Enter-PSHostProcess -Id 4308 -AppDomainName DscPsPluginWkr_AppDomain
Debug-Runspace -Id 22
VERBOSE: [SQL2016]: LCM:  [ End    Test     ]  [[xSQLServerSetup]localhost]  in 0.1410 seconds.
PowerShell DSC resource MSFT_xSQLServerSetup  failed to execute Test-TargetResource functionality with error message: 
Object reference not set to an instance of an object. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
VERBOSE: [SQL2016]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 0.887 seconds

I have tried  to setup default values for the parameters and remove ALL logics in Test-TargetResource, it still returns same error.

### PR DESCRIPTION
**Pull request by nesith**
#### Pull Request (PR) description
- Changes to SqlSetup
  - Changed the logic of how default value of FailoverClusterGroupName is
    set since that was preventing the resource to be able to be debugged
    ([issue #448](https://github.com/PowerShell/SqlServerDsc/issues/448)).

#### This Pull Request (PR) fixes the following issues
- Fixes #448 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1301)

### CODE REVIEW

**Comment by nesith** [comment]
@johlju PR

**Comment by johlju** [comment]
There are merge conflicts since your PR was not based on the latest changes. Could you please rebase against branch dev using `git rebase` (not by using `git pull` or `git merge`, to keep the commit history). If you don't know how to rebase your local dev and working branch, please look at how to [Resolve merge conflicts](https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts).
Let me know if you need any assistance.

**Comment by nesith** [comment]
Sorry had a very busy couple of weeks at work, I will fix the issues sometime this week.

**Comment by johlju** [comment]
@nesith no worries. Looking forward merging this. 🙂

**Comment by johlju** [comment]
When you have time to work on this, then this PR need to be rebased too because of changes been merged into dev 😃

**Comment by nesith** [comment]
@johlju Hi, Seems the chnages I made to the dynamic variables as per your comments are breaking the tests, I will have a look at this this weekend

**Comment by johlju** [comment]
@nesith sounds great! :) Let me know when you are done and I continue the review.

**Comment by johlju** [comment]
Closing and reopening to kick off the tests again,

**Comment by johlju** [comment]
@nesith Thank you sending in this PR! I took it over the finish line now. 🙂

**Pull request merged**
