### PR TITLE
SqlAGReplica: Fix read-only routing list reaching desired state

### LINKED ISSUE #1305: SqlAGReplica: Test doesn't check ReadOnlyRoutingList properly
#### Details of the scenario you tried and the problem that is occurring
```
$configurationData = @{
    AllNodes = @(
        @{
            NodeName = '*'
            PsDscAllowPlainTextPassword = $true
            PsDscAllowDomainUser = $true
        }
        @{
         NodeName = 'localhost'
        }
    )
}

configuration Blah {
    param(
        $Credential
    )
    Import-DscResource -Module SqlServerDsc

    Node $AllNodes.NodeName {    
        SqlAGReplica SEC1N1 {
            ServerName = 'SEC1N1'
            InstanceName = 'MSSQLSERVER'

            AvailabilityGroupName = 'AG1'
            Name = 'SEC1N1'
            ReadOnlyRoutingConnectionUrl = 'tcp://SEC1N1.lab.com:1433'
            ReadOnlyRoutingList = 'SEC1N2', 'SEC1N3'
            PsDscRunAsCredential = $Credential
        }
    }
}

if (!$credential) { $credential = Get-Credential LAB\LocalAdministrator }
Blah -Credential $credential -ConfigurationData $configurationData
Start-DscConfiguration -Force -Wait -Verbose -Path Blah
```

Although ReadOnlyRoutingList gets set properly, if you run the code a second time you get this result.

```
VERBOSE: [CHWK01]: LCM:  [ Start  Test     ]  [[SqlAGReplica]SEC1N1]
VERBOSE: [CHWK01]:                            [[SqlAGReplica]SEC1N1] Importing the module MSFT_SqlAGReplica in force mode.
VERBOSE: [CHWK01]:                            [[SqlAGReplica]SEC1N1] Importing the module MSFT_SqlAGReplica in force mode.
VERBOSE: [CHWK01]:                            [[SqlAGReplica]SEC1N1] Preferred module SqlServer found.
VERBOSE: [CHWK01]:                            [[SqlAGReplica]SEC1N1] Importing PowerShell module 'SqlServer' with version '21.0.17279' from path 'C:\Program Files\WindowsPowerShell\Modules\SqlServer\SqlServer.psm1'.
VERBOSE: [CHWK01]:                            [[SqlAGReplica]SEC1N1] Connected to SQL instance 'SEC1N1'.
VERBOSE: [CHWK01]:                            [[SqlAGReplica]SEC1N1] 2019-03-14_00-14-48: 'ReadOnlyRoutingList' should be 'SEC1N2 SEC1N3' but is 'SEC1N2 SEC1N3'
```

It will trigger Set again, which does nothing, and so never reaches desired state.

#### Suggested solution to the issue
In the Test code there's a -ne comparison which isn't valid for the ReadOnlyRoutingList being a string array (it's the only one).

```
                    if ( $getTargetResourceResult.($parameterName) -ne $parameterValue )
                    {
                        New-VerboseMessage -Message "'$($parameterName)' should be '$($parameterValue)' but is '$($getTargetResourceResult.($parameterName))'"

                        $result = $False
                    }
```

To fix this the ReadOnlyRoutingList parameter can have an explicit different case that uses a string join with commas instead of the -ne comparison. That's how it's done in the Set portion and that bit is working great.

```
                    if ( ( $submittedParameters -contains 'ReadOnlyRoutingList' ) -and ( ( $ReadOnlyRoutingList -join ',' ) -ne ( $availabilityGroupReplica.ReadOnlyRoutingList -join ',' ) ) )
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

### PR DESCRIPTION
**Pull request by codykonior**
#### Pull Request (PR) description
This fixes the Test-Resource portion of SqlAGReplica so that it compares read only routing lists properly. This allows desired state to be reached.

I added no entry in CHANGELOG as it's fixing the unreleased feature.

In the unit tests I modified the read only routing list defaults. Using an array instead of a single server name here causes the tests to fail on the old code (as they should) and pass on the new code (as they should). 

In the unit tests I also added another section to confirm that the test resource passes when nothing has changed. This also picked up the old bad code and passes on the new code.

Finally I did a search replace of $True and $False.

#### This Pull Request (PR) fixes the following issues
- Fixes #1305

#### Task list
- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1312)

### CODE REVIEW

**Comment by mdaniou** [comment]
___
*[DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.psm1, line 671 at r1](https://reviewable.io/reviews/powershell/sqlserverdsc/1312#-LaOn-cNBaLb5zMBPJvK:-LaOn-cO4yo4T96zgGTI:bgrfxj) ([raw file](https://github.com/powershell/sqlserverdsc/blob/f63f7712a5b53d0916ba5991fb4c049fd0f8fa65/DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.psm1#L671)):*
> ```PowerShell
>                     if ( $parameterName -eq 'ReadOnlyRoutingList' )
>                     {
>                         $different = ( $getTargetResourceResult.($parameterName) -join ',' ) -ne ( $parameterValue -join ',' )
> ```

Is this working with Load-Balancing read-only routing list ?
Sth like (('Server1','Server2'), 'Server3')

**Comment by mdaniou** [comment]
___
*[DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.psm1, line 671 at r1](https://reviewable.io/reviews/powershell/sqlserverdsc/1312#-LaMZRCe1P3EucOnavyP:-LaOnR1c8BXMzc7MGvXZ:bo9y6jr) ([raw file](https://github.com/powershell/sqlserverdsc/blob/f63f7712a5b53d0916ba5991fb4c049fd0f8fa65/DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.psm1#L671)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $different = ( $getTargetResourceResult.($parameterName) -join ',' ) -ne ( $parameterValue -join ',' )
> ```

what if `$getTargetResourceResult.($parameterName)` returns `@('Server1', 'Server2')`, but `parameterValue` returns `@('Server2', 'Server1')`. Can that happen? *Feel like I have asked this before?* :smile:
</blockquote></details>

The test has to fail if it happens. An attempt to connect to replicas of this list will be using round-robin until there is a success. Hence you want the order to be respected otherwise you might send read-only transactions to the Primary which is probably not what you want :)

**Comment by mdaniou** [comment]
___
*[DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.psm1, line 671 at r1](https://reviewable.io/reviews/powershell/sqlserverdsc/1312#-LaOn-cNBaLb5zMBPJvK:-LaOocpZ8Jve_F471DNV:b-4rnwmb) ([raw file](https://github.com/powershell/sqlserverdsc/blob/f63f7712a5b53d0916ba5991fb4c049fd0f8fa65/DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.psm1#L671)):*
<details><summary><i>Previously, mdaniou (Maxime Daniou) wrote…</i></summary><blockquote>

Is this working with Load-Balancing read-only routing list ?
Sth like (('Server1','Server2'), 'Server3')

</blockquote></details>

https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-read-only-routing-for-an-availability-group-sql-server?view=sql-server-2017#loadbalancing

**Comment by johlju** [comment]
@mdaniou merging this as an issue has been opened to track the issue you raised. Thanks for pointing that out! And thanks to @codykonior for opening an issue to track it!

**Pull request merged**
