### PR TITLE
SqlServerDatabaseMail: New resource for configuring Database Mail

### LINKED ISSUE #155: SqlServerDatabaseMail: New resource
xdBmail is an additional resource I've been developing to setup the default database mail profile and account during SQL roll out.

Usage - configure a default mail profile for SQL agent jobs and alerts.

### PR DESCRIPTION
**Pull request by SQLHorizons**
**Pull Request (PR) description**
- Changes to SqlServerDsc
  - Added new resource SqlServerDatabaseMail for configuring SQL Server
    database mail.

**This Pull Request (PR) fixes the following issues:**
Fixes #155

**Task list:**

- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/145)

### CODE REVIEW

**Comment by johlju** [comment]
@SQLHorizons You need to resolve the check that failed to be able to get a review on this PR. See the failed test here https://ci.appveyor.com/project/PowerShell/xsqlserver/build/2.0.369.0
Looks like you have the wrong encoding on the module file, if you change the file encoding to UTF-8 I think the test will be happy.

Could you also please change the name of the resource to something that starts with 'MSFT_xSQLServer', like 'MSFT_xSQLServerDatabaseMail'. Only place where the prefix 'MSFT_' should not be used in in the friendly name in the schema.mof file (see other resources for examples).

**Comment by johlju** [comment]
@SQLHorizons Also make sure all files end with a blank line.

**Comment by SQLHorizons** [comment]
@johlju thank you for your input, made the changes, but still got some work on this as its only good for creating the account from scratch.  I know what I need to do, just got to find the time.

**Comment by johlju** [comment]
@SQLHorizons It's good work so far! Hope you get the time to finish this soon, I know what you mean about finding time. Let us know if you need any help! We are here for each other! :smile:

Some suggestions after a quick glance of your code
* Rename the resource as suggested in previous comment.
* Add an `Ensure` parameter so you can add database mail (`Ensure = 'Present'`) and remove database mail (`Ensure = 'Absent'`).
* Look add the helper functions to see if there are function that will help you and improve your code (like `Import-SQLPSModule`, `New-TerminatingError` and `Connect-SQL`).
 - Helper function is here: https://github.com/PowerShell/xSQLServer/blob/dev/xSQLServerHelper.psm1
* Follow the StyleGuideline.md here https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md.
* You need to write a test for the resource 
 - Guideline here: https://github.com/johlju/DscResources/blob/master/TestsGuidelines.md
 - Template here: https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md

You can find all the guidelines here: https://github.com/PowerShell/DscResources

**Comment by kwirkykat** [comment]
@SQLHorizons @johlju I agree this resource needs to be renamed. I like @johlju's suggestion of  'MSFT_xSQLServerDatabaseMail'.

**Comment by SQLHorizons** [comment]
@johlju, @kwirkykat Agreed will see what I can do over the next week, and yes will go with the name suggestion.

**Comment by johlju** [comment]
@SQLHorizons don't want to rush you in anyway. Just curious if you had gotten some time to start look at this. Let us know if you need any help. :smile:

**Comment by SQLHorizons** [comment]
@johlju sorry been busy with a lot of other stuff lately, am I holding something up?

**Comment by johlju** [comment]
No, you are not holding anything up. Was just checking status :) And I'm looking forward getting this resource into the module :)

**Comment by johlju** [comment]
@SQLHorizons Do you have time to finish this one? If you feel that you don't have time, then please tick 'Allow edits from maintainers' to the right here, around Notifications. Then I can help you get this finished.

In the meantime I label this one as abandoned.

**Comment by johlju** [comment]
@SQLHorizons Great that it was ticked. I can help an see if I can help get this PR thru.

Side note: I can't see if they are ticked, I raised an issue to GitHub and asked for them to add the checkbox, grayed out, for all (or at least maintainers), so that I can see the status and don't have to ask every time. 😄

**Comment by johlju** [comment]
Closing an reopening to get correct CLA status.

**Comment by johlju** [comment]
Renamed this resource to align with new naming convention - please suggest other name if someone thinks `SqlServerDatabaseMail` is not appropriate. 

I will try to work on this in the next couple of weeks so we can get this one to the finish line since it been in PR for over a year. 😄 @SQLHorizons was kind enought to tick the Allow edits from maintainers, so I can continue the work in the same PR.
@SQLHorizons if you feel taking over the work at any point, just let me know and I'm happy to hand you the reins.

**Comment by johlju** [comment]
Reviewed 6 of 11 files at r7.
Review status: 6 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[README.md, line 144 at r7](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145#-L1SCdeyz0Z5lBGOc_yy:-L1SCdeyz0Z5lBGOc_yz:b-rmthhh) ([raw file](https://github.com/powershell/sqlserverdsc/blob/a41c500ac2b2632e353b3762fa68fd0a909ed233/README.md#L144)):*
> database mail

Database Mail (it's a feature name)

---

*[README.md, line 829 at r7](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145#-L1SCjxj2eteqJWgiDim:-L1SCjxj2eteqJWgiDin:b-s65f30) ([raw file](https://github.com/powershell/sqlserverdsc/blob/a41c500ac2b2632e353b3762fa68fd0a909ed233/README.md#L829)):*
> ```Markdown
> ### SqlServerDatabaseMail
> 
> Resource to manage SQL Server database mail.
> ```

Same as previous comment. Throughout.

---

*[DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1, line 9 at r7](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145#-L1SBDZCMDtkNYJNvZOf:-L1SBDZCMDtkNYJNvZOg:b-k4i9wl) ([raw file](https://github.com/powershell/sqlserverdsc/blob/a41c500ac2b2632e353b3762fa68fd0a909ed233/DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1#L9)):*
> '{0}\{1}'

This should be double backslashes.

---

*[DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1, line 11 at r7](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145#-L1SBQJ7EfuKJy01LxuF:-L1SBQJ7EfuKJy01LxuG:bk7f906) ([raw file](https://github.com/powershell/sqlserverdsc/blob/a41c500ac2b2632e353b3762fa68fd0a909ed233/DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1#L11)):*
> returning current

returning the current...

---

*[DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1, line 14 at r7](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145#-L1SBK29sO2rbBaSC1Lf:-L1SBK29sO2rbBaSC1Lg:bs84cbh) ([raw file](https://github.com/powershell/sqlserverdsc/blob/a41c500ac2b2632e353b3762fa68fd0a909ed233/DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1#L14)):*
> '{1}\{2}'

This should be double backslashes.

---

*[DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1, line 15 at r7](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145#-L1SBXybaVVSwA9d3RuV:-L1SBXybaVVSwA9d3RuW:b-mv1dog) ([raw file](https://github.com/powershell/sqlserverdsc/blob/a41c500ac2b2632e353b3762fa68fd0a909ed233/DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1#L15)):*
> Changing SQL

Changing the SQL...

---

*[DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1, line 19 at r7](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145#-L1SBfbpBVqasTjPpeth:-L1SBfbpBVqasTjPpeti:b83bqp1) ([raw file](https://github.com/powershell/sqlserverdsc/blob/a41c500ac2b2632e353b3762fa68fd0a909ed233/DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1#L19)):*
> {0}, expected {1}

'{0}', expected '{1}'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145)*

**Comment by johlju** [comment]
Review status: 3 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[README.md, line 144 at r7](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145#-L1SCdeyz0Z5lBGOc_yy:-L1SWmTsx3CXtgDbO032:bb6un1j) ([raw file](https://github.com/powershell/sqlserverdsc/blob/a41c500ac2b2632e353b3762fa68fd0a909ed233/README.md#L144)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> database mail

Database Mail (it's a feature name)
</blockquote></details>

Done

---

*[README.md, line 829 at r7](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145#-L1SCjxj2eteqJWgiDim:-L1SWn87zjIcUryx0KJV:bb6un1j) ([raw file](https://github.com/powershell/sqlserverdsc/blob/a41c500ac2b2632e353b3762fa68fd0a909ed233/README.md#L829)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same as previous comment. Throughout.
</blockquote></details>

Done

---

*[DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1, line 9 at r7](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145#-L1SBDZCMDtkNYJNvZOf:-L1SWidyvXzmqTYkZYZG:bb6un1j) ([raw file](https://github.com/powershell/sqlserverdsc/blob/a41c500ac2b2632e353b3762fa68fd0a909ed233/DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1#L9)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> '{0}\{1}'

This should be double backslashes.
</blockquote></details>

Done

---

*[DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1, line 11 at r7](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145#-L1SBQJ7EfuKJy01LxuF:-L1SWjPPcM8Y1j5Cr7wx:bb6un1j) ([raw file](https://github.com/powershell/sqlserverdsc/blob/a41c500ac2b2632e353b3762fa68fd0a909ed233/DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1#L11)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> returning current

returning the current...
</blockquote></details>

Done

---

*[DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1, line 14 at r7](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145#-L1SBK29sO2rbBaSC1Lf:-L1SWk-CmFCq2hSAMHHp:bb6un1j) ([raw file](https://github.com/powershell/sqlserverdsc/blob/a41c500ac2b2632e353b3762fa68fd0a909ed233/DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1#L14)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> '{1}\{2}'

This should be double backslashes.
</blockquote></details>

Done

---

*[DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1, line 15 at r7](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145#-L1SBXybaVVSwA9d3RuV:-L1SWkTtQJJsp7qQJeYS:bb6un1j) ([raw file](https://github.com/powershell/sqlserverdsc/blob/a41c500ac2b2632e353b3762fa68fd0a909ed233/DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1#L15)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Changing SQL

Changing the SQL...
</blockquote></details>

Done

---

*[DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1, line 19 at r7](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145#-L1SBfbpBVqasTjPpeth:-L1SWl2EmmKVNnhhQ4yJ:bb6un1j) ([raw file](https://github.com/powershell/sqlserverdsc/blob/a41c500ac2b2632e353b3762fa68fd0a909ed233/DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1#L19)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> {0}, expected {1}

'{0}', expected '{1}'
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145)*

**Comment by johlju** [comment]
Reviewed 3 of 6 files at r8.
Review status: 6 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145)*

**Comment by johlju** [comment]
@PlagueHO would you mind reviewing this one for me? I pushed a lot of commits to this PR so would be nice to have someone else look over it. Especially grammar 😉 It's kind of big PR, so no hurry. 
I did a quick review (not all files) to find simple mistakes, but it's probably gonna be a lot more. 😄

**Comment by johlju** [comment]
Review status: 3 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[README.md, line 824 at r9](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145#-L20-WZBymEhmawXaTGV:-L20-WZBymEhmawXaTGW:b2mjyp4) ([raw file](https://github.com/powershell/sqlserverdsc/blob/052ebc595dbe11c195c9ec14790b856eea8dfd2f/README.md#L824)):*
> ```Markdown
> * Target machine must be running Windows Server 2008 R2 or later.
> * Target machine must be running SQL Server Database Engine 2008 or later.
> * Target machine must be running SQL Server Agent.
> ```

This entry is on the wrong resource.

---

*[README.md, line 882 at r9](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145#-L20-zhUJEs6NwNgA_y4:-L20-zhUJEs6NwNgA_y5:b-oxv6ui) ([raw file](https://github.com/powershell/sqlserverdsc/blob/052ebc595dbe11c195c9ec14790b856eea8dfd2f/README.md#L882)):*
> ```Markdown
> #### Examples
> 
> None.
> ```

Should be updated with the examples here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145)*

**Comment by johlju** [comment]
Reviewed 1 of 6 files at r3, 2 of 4 files at r6, 2 of 11 files at r7, 3 of 6 files at r8, 1 of 3 files at r9, 2 of 3 files at r10, 3 of 3 files at r11.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 25 at r11](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145#-L20wAmNBL74tnpPnXbj:-L20wAmNBL74tnpPnXbk:b-fpsct6) ([raw file](https://github.com/powershell/sqlserverdsc/blob/20fdc90fe6c74b2ccc29b4ccb7e9d30b0d2204d1/CHANGELOG.md#L25)):*
> Updated Test-SQLDscParameterState

Updated helper function...

---

*[DSCResources/MSFT_SqlServerDatabaseMail/MSFT_SqlServerDatabaseMail.psm1, line 184 at r11](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145#-L20wUVC8Mg5tQWXrZ6e:-L20wUVC8Mg5tQWXrZ6f:b-p9z6eq) ([raw file](https://github.com/powershell/sqlserverdsc/blob/20fdc90fe6c74b2ccc29b4ccb7e9d30b0d2204d1/DSCResources/MSFT_SqlServerDatabaseMail/MSFT_SqlServerDatabaseMail.psm1#L184)):*
> ```PowerShell
>         Creates or removes the Database Mail configuration.
> 
>         Information about the different properties can be found here
> ```

Move this to .NOTES.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145)*

**Comment by johlju** [comment]
Reviewed 1 of 6 files at r3, 1 of 4 files at r6, 4 of 4 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145)*

**Comment by johlju** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/145#-:-L20yJGmmLwmUN1sYSx-:bnfp4nl)*

**Comment by johlju** [comment]
@SQLHorizons took a while, but now finally the work you started has been merged! Thanks for your work! 😄

**Pull request merged**
