### PR TITLE
SqlDatabaseRecoveryModel: Database name can now be a pattern 

### PR DESCRIPTION
**Pull request by dcrreynolds**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1052)

### CODE REVIEW

**Comment by johlju** [comment]
@dcrreynolds thanks for sending in this PR! I think this has potential, but I have some thoughts around this change. Do you have a thought on how to solve the below?

Since the parameter `Name` is a Key. Then if I add two resources like below that would be allowed (configuration would compile), but this would yield a ping-pong behavior where both will always be `false`. 

```
Configuration Example
{
    Import-DscResource -ModuleName SqlServerDsc

    node localhost
    {
        SqlDatabaseRecoveryModel MyDbWildcardToFull
        {
            Name                 = 'MyDb*'
            RecoveryModel        = 'Full'
            ServerName           = 'sqltest.company.local'
            InstanceName         = 'DSC'
        }

        SqlDatabaseRecoveryModel MyDbTestToSimple
        {
            Name                 = 'MyDbTest'
            RecoveryModel        = 'Simple'
            ServerName           = 'sqltest.company.local'
            InstanceName         = 'DSC'
        }
    }
}
```

**Comment by dcrreynolds** [comment]
I feel like that is a systemic issue of DSC, lots of DSC resources can ping pong in between themselves. We also see the same behavior with DSC and GPO or other methods of configuration. 

We could have the resource log somewhere which recovery models have been configured, but something about that ideas feels like it could be problematic.

I have never seen codecov before. What is the failure trying to tell me?

**Comment by johlju** [comment]
@randomnote1 and others in the community, please can I get your input on this one? How do you see this change in relation to SqlAGDatabase?

Since SqlAGDatabase uses wildcards for the database names added to the AG I'm thinking that this change would help a lot. But at the same time I don't like the idea of introducing a potential ping-pong behavior. But maybe the pros are higher than the cons? 
 
@dcrreynolds I think we cannot take in account changes made by other tools (like GPO), we have to see such change as a manual change, if the configuration is not in desired state then the configuration will be updated to be in desired state. But we can try make sure the configurations will not contradict each other.
Using a log as you say don't seem to be the best approach.

**Comment by johlju** [comment]
@dcrreynolds Codecov is complaining because there are not high enough code coverage with this change. Project has 97% coverage, this PR has 38% coverage of the code. You see in the https://github.com/PowerShell/SqlServerDsc/pull/1052#issuecomment-369122954 that 16 rows less are hit and missed rows increased with 23 rows. Also, the tests are failing which might result in some of these hits and misses.
To solve this you need to make sure the tests passes and add unit tests to cover this change. I did not mention that before because I wanted to discuss the design first. 😄

**Comment by randomnote1** [comment]
I think that the `SqlDatabaseRecoveryModel` resource differs fundamentally from `SqlAGDatabase` because it defines the database(s) that are to be a member of a specified Availability Group. `SqlDatabaseRecoveryModel` is defining a property on a database.

I do see @johlju's point about ping-pong behavior. But, this behavior could potentially be seen in a resource like `SqlDatabaseRecoveryModel` because of the wildcards used in defining the database membership. If a database matches a wildcard in two or more resources, it will throw an error at runtime when attempting to add the database to the second AG.

With all that said, I do like the idea of being able to specify a property on a database via wildcards or RegEx as I see it being immensely valuable in my own work. I think the risk of the potential ping-pong behaviour is acceptable, however we need to ensure the feedback to the end user is extremely clear. Otherwise troubleshooting the ping-pong behavior will be a nightmare.

Could we possible surface an informational message in the SQL log when the change is made? Maybe something like `The recovery model on database '<database name>' has been changed from '<old recovery model>' to '<new recovery model>' by DSC based on the pattern '<pattern>'.`. This would add some work, but might make it much more friendly to troubleshoot.

**Comment by johlju** [comment]
@randomnote1 Thank you for that insight! 

I agree logging this would be the best. Maybe we could log an event using [xp_logevent](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/xp-logevent-transact-sql)? Is there another (better) way?
Using xp_logevent would probably require a certain permission level on the account running the resource, that permission must be documented. Also, if the required permission is high, then maybe we should only log to SQL Server log when a wildcard/regex is assigned to `Name`, making it possible to use lower permission when not using wildcard/regex (permission to make changes to only the particular database).

So far pros over weigh the cons - so unless someone else objects we can continue doing this change, with the suggested changes.

**Comment by johlju** [comment]
Maybe we should add a optional parameter `UseWildcard` or `UseRegularExpression` that we use to switch the behavior of the resource?

**Comment by randomnote1** [comment]
We had discussed adding flags to the `SqlAgDatabase` resource and decided that it was unnecessary to add the overhead of the additional parameters. Theoretically it is possible to analyze the string coming in to determine if it is a wildcard or regex pattern. I'll have to defer to folks smarter than myself to discuss the merits of that.

**Comment by randomnote1** [comment]
For logging, `xp_logevent` may require too high of a permissions level. However, it is highly likely that the `PsDscRunAsCredential` is already a member of `sysadmin`.

Maybe we could utilize [`RAISEERROR`](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/raiserror-transact-sql) to work around the permissions requirement.

**Comment by dcrreynolds** [comment]
Great conversation. I'll work to roll in the discussed changes and fix the codecov/test issues. Thanks!

**Comment by johlju** [comment]
`RAISEERROR` will update both SQL Server log and the Event Log, so I think we should only use `RAISEERROR` if it does not generate an Error entry in the Event Log. I see that we should preferably generate an information entry in the Event Log. A warning entry might work to, but en error entry could kick of errors in monitoring tools, and we don't want that. 
If `RAISEERROR` can generate information or warning entries then I agree to use `RAISEERROR`.

@dcrreynolds I agree, great conversation! When we in the community work together we get the best result! All opinions matter, wish more people had time to comment on stuff.

**Comment by johlju** [comment]
@dcrreynolds the method that you will use to write to the SQL Server log, please add that as an helper function in the helper module [SqlServerDscHelper](https://github.com/PowerShell/SqlServerDsc/blob/dev/SqlServerDscHelper.psm1). I see that this could potentially be used more widely to write log information by other resources too.

**Comment by dcrreynolds** [comment]
After some testing, it seems that RAISEERROR can generate information log entries, but does require the user to be a member of the sysadmin fixed server role or a user with ALTER TRACE permissions. 

I also learned that the SQL is generating a similar message in the SQL and app longs when it makes the change. "Setting database option RECOVERY to FULL for database 'SP_Search'." The only difference is it doesn't say why the change was made.

Does the built in logging provide enough info? Are we ok with the requirements for RAISEERROR?

**Comment by johlju** [comment]
@dcrreynolds What happens if the user does not have that permission? No information log entry in the Application Event Log, but in the SQL Server log? Or no log information at all in either Application Event Log or the SQL Server log?

The point that @randomnote1 made was that it do write _why_ it changed or _whom_ changed it, so it would be easier to determine what causing the change.

Depending on the answer to the questions above, I would be OK with the permission requirement for the RAISEERROR, if that is a requirement _only_ when using the resource with a wildcard. When not using a wildcard I don't see the need for logging, since the resource could be run with a user with less privileges. I can be swayed to write a log even without a wildcard, but that would mean a breaking change.

**Comment by johlju** [comment]
Labeling this PR as abandoned since it has gone 14 days or more since the last update. An abandoned PR can be continued by another contributor. The abandoned label will be removed if work on the PR is taken up again.

**Comment by johlju** [comment]
Reopening this PR as it was wrongly closed by GitHub All Stale due to miss configuration. It still labeled as abandoned. An abandoned PR can be continued by another contributor. The abandoned label will be removed if work on the PR is taken up again.

**Comment by dcrreynolds** [comment]
Hi there! Sorry for sitting on this for so long. I've made a small update that shows one way using RaiseError could look like for logging the change. Once we get to a method that we like, I will fix up the test. I've attached what the SQL logs and application logs show when DSC makes a change.
eventlogss
sqlserverlogss

**Comment by johlju** [comment]
Relabeled this as 'needs investigating' (by community).

**Comment by johlju** [comment]
It looks to me like what was asked for. 

The messages text does in the screen dumps does not contain 'PowerShell Desired State Configuration Updated...'. See the text in the code. I assume you took the screen dumps before making the final message text?

Nobody have objected, so go with his.

**Comment by dcrreynolds** [comment]
good to go!

**Comment by johlju** [comment]
@dcrreynolds just pinging to see if you have time to work on this?

**Comment by dcrreynolds** [comment]
Hi! Yes I can finish this up. I didn't realize this had gotten to be over a year old!

**Comment by johlju** [comment]
@dcrreynolds Time flies when one are having fun 😄 Would be great to get this merged. I hope it is easy to rebase this one after this long.

**Comment by dcrreynolds** [comment]
Hi! I haven't forgotten about this, spent some time merging everything in tonight. For the review above, I have made most changes. 

I do think keeping the logic using the like competitor is better than using match. Using match will break a lot of backwards compatibility since it will likely accidentally start applying to a lot of new DBs. 

I've added a read-only property named DatabaseInfo that is a Hashtable of DBName and RecoveryMode. This is currently configured to only include matching DB names to avoid confusion. The RecoveryModel parameter was left unchanged since returning the desired model as opposed to the actual would lead to some confusion. A comma separated list is informative without dropping data, allows for a quick status comparison, and the new hashtable supports better access programatically. 

Let me know if all of this works for you.

**Comment by johlju** [comment]
@dcrreynolds will be great to get this to the finish line. I read you comments. Since it was a while ago, would you mind go into Reviewable and write 'Done' on the review comments that is fixed, and add the respective comments you made in the previous comment inside the Reviewable so I understand the context. 🙂 

Also, You said you merged changes into your working branch, but I don't see any new commits here yet. Did you (force) push the changes?  I guess that you also resolved the conflicts since you merged the recent changes.

**Comment by johlju** [comment]
Closing this PR due to inactivity. If there are someone who wants to work on this issue or PR please open a new PR.

**Pull request closed without merging**
