### PR TITLE
SQLAlias: Fix for issue 949

### LINKED ISSUE #949: SQLAlias throws error on 32 bit alias
**Details of the scenario you tried and the problem that is occurring:**
On line 165 of SQLAlias the registry key for the 32 bit alias is created. On a new test environment, the MSSQLServer key (and all child keys) didn't exist yet, resulting in an error when creating the key.

After some troubleshooting I found that New-Item only creates child keys when the parent exists. When the parent does not exist, an error is thrown. This can be resolved by adding the -Force parameter to the cmdlet.

This change is also required for line 152.

**The DSC configuration that is using the resource (as detailed as possible):**
SQLAlias Alias
{
            Ensure               = "Present"
            Name                 = "DBServer"
            ServerName       = "serverx.domain.com"
            Protocol             = 'TCP'
            TcpPort              = 1433
}

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Windows Server 2016

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
xSQLServer 9.0

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
9.0

### PR DESCRIPTION
**Pull request by ykuijs**
**Pull Request (PR) description**
Fix for issue #949 where creation of the alias failed if the reg keys did not exist

**This Pull Request (PR) fixes the following issues:**
Fixes #949 

**Task list:**
- [X] Change details added to Unreleased section of CHANGELOG.md?
- [X] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [X] Examples appropriately updated?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/950)

### CODE REVIEW

**Comment by johlju** [comment]
I got stuck with the flu, so will review this once my head is back in the game again. :)

**Comment by johlju** [comment]
@ykuijs It's looking good. Just need a rebase to fix the CHANGELOG.md since a new version was release while this was in PR.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/950#-:-L0YmqTpyReGTYH48rk8:beu7f5y)*

**Comment by ykuijs** [comment]
Done, AppVeyor checks are running now

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/950#-:-L0jBQCnaeJTozf5Wzbv:bgcr4gd)*

**Comment by johlju** [comment]
Still seeing the entry in the wrong place in the change log :/

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 125 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/950#-L0nBQqVPADeC_xhoTe5:-L0nBQqVPADeC_xhoTe6:b2ubopl) ([raw file](https://github.com/powershell/sqlserverdsc/blob/a807183d2d0643baf06f12edd718139c52b67706/CHANGELOG.md#L125)):*
> ```Markdown
>     to ServerName and InstanceName respectively
>     ([issue #308](https://github.com/PowerShell/SqlServerDsc/issues/308)).
> - Changes to SqlAlias
> ```

This should be moved to the Unreleased section.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/950#-:-L0nBlM0LagAYfsUNA1P:b-kwrzhg)*

**Comment by ykuijs** [comment]
Ok, my bad. Thought you meant something different before. Moved the change to the Unreleased section now. AppVeyor checks have completed successfully.

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 125 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/950#-L0nBQqVPADeC_xhoTe5:-L0sHLYz9s7Z3h6cG_GI:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/a807183d2d0643baf06f12edd718139c52b67706/CHANGELOG.md#L125)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This should be moved to the Unreleased section.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/950#-:-L0sH2P1J-6R3dIkOyJ6:b85e571)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/950#-:-L0so5T-Ff-7gUfcW231:bnfp4nl)*

**Comment by johlju** [comment]
@ykuijs No worries. Sometimes I'm bad at explaining too 😄  Great work on this one! Merged now!

**Pull request merged**
