### PR TITLE
SqlRs: [#1258] Fix for Reporting Services initialization

### LINKED ISSUE #1258: SqlRs: SQL Server 2016 SSRS init fails on AWS
#### Details of the scenario you tried and the problem that is occurring
We have a configuration that we run against a provisioned AWS VM Windows Server 2016 + SQL Server 2016 SP1 Standard. (We use the latest AMI that matches the name pattern Windows_Server-2016-English-Full-SQL_2016_SP1_Standard*)

Our set of partial configurations is not trivial - we have a workflow that compiles and pushes these configurations to the target server. One of the first things it does is set the machine name, which causes a reboot. Our workflow then waits for the machine to boot back up and then waits for the configuration run to finish.

Recently, we noticed that after a while the workflow starts reporting that DSC has encountered an error, but there's nothing in the Event Log. However, there is an entry in the log file:

#### Verbose logs showing the problem
```
  {"time": "2018-12-14T15:26:07.040+00:00", "type": "verbose", "message": "[HOSTING-TEST]: LCM:  [ Start  Resource ]  [[SqlRS]SSRSConfig]  "},
  {"time": "2018-12-14T15:26:07.040+00:00", "type": "verbose", "message": "[HOSTING-TEST]: LCM:  [ Start  Test     ]  [[SqlRS]SSRSConfig]  "},
  {"time": "2018-12-14T15:26:07.103+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\\Microsoft\\SQLServer\\ReportServer\\RS_MSSQLSERVER\\v13\\Admin,'className' = MSReportServer_ConfigurationSetting'."},
  {"time": "2018-12-14T15:26:07.930+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Operation 'Enumerate CimInstances' complete."},
  {"time": "2018-12-14T15:26:07.952+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] 2018-12-14_15-26-07: Reporting services localhost\\MSSQLSERVER are not initialized."},
  {"time": "2018-12-14T15:26:07.957+00:00", "type": "verbose", "message": "[HOSTING-TEST]: LCM:  [ End    Test     ]  [[SqlRS]SSRSConfig]  in 0.9170 seconds."},
  {"time": "2018-12-14T15:26:07.958+00:00", "type": "verbose", "message": "[HOSTING-TEST]: LCM:  [ Start  Set      ]  [[SqlRS]SSRSConfig]  "},
  {"time": "2018-12-14T15:26:08.007+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\\Microsoft\\SQLServer\\ReportServer\\RS_MSSQLSERVER\\v13\\Admin,'className' = MSReportServer_ConfigurationSetting'."},
  {"time": "2018-12-14T15:26:08.031+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Operation 'Enumerate CimInstances' complete."},
  {"time": "2018-12-14T15:26:08.034+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root/cimv2,'className' = Win32_OperatingSystem'."},
  {"time": "2018-12-14T15:26:08.060+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Operation 'Enumerate CimInstances' complete."},
  {"time": "2018-12-14T15:26:08.064+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] 2018-12-14_15-26-08: Initializing Reporting Services on localhost\\MSSQLSERVER."},
  {"time": "2018-12-14T15:26:08.068+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] 2018-12-14_15-26-08: Setting report server virtual directory on localhost\\MSSQLSERVER to ReportServer."},
  {"time": "2018-12-14T15:26:08.090+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Perform operation 'Invoke CimMethod' with following parameters, ''instance' = MSReportServer_ConfigurationSetting (InstanceName = \"MSSQLSERVER\"),'methodName' = SetVirtualDirectory,'namespaceName' = root/Microsoft/SQLServer/ReportServer/RS_MSSQLSERVER/v13/Admin'."},
  {"time": "2018-12-14T15:26:12.634+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Operation 'Invoke CimMethod' complete."},
  {"time": "2018-12-14T15:26:12.647+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] 2018-12-14_15-26-12: Adding report server URL reservation on localhost\\MSSQLSERVER: http://+:8888."},
  {"time": "2018-12-14T15:26:12.648+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Perform operation 'Invoke CimMethod' with following parameters, ''instance' = MSReportServer_ConfigurationSetting (InstanceName = \"MSSQLSERVER\"),'methodName' = ReserveUrl,'namespaceName' = root/Microsoft/SQLServer/ReportServer/RS_MSSQLSERVER/v13/Admin'."},
  {"time": "2018-12-14T15:26:17.700+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Operation 'Invoke CimMethod' complete."},
  {"time": "2018-12-14T15:26:17.701+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] 2018-12-14_15-26-17: Adding report server URL reservation on localhost\\MSSQLSERVER: https://hosting-test.elements.symplectic.org:443."},
  {"time": "2018-12-14T15:26:17.702+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Perform operation 'Invoke CimMethod' with following parameters, ''instance' = MSReportServer_ConfigurationSetting (InstanceName = \"MSSQLSERVER\"),'methodName' = ReserveUrl,'namespaceName' = root/Microsoft/SQLServer/ReportServer/RS_MSSQLSERVER/v13/Admin'."},
  {"time": "2018-12-14T15:26:23.254+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Operation 'Invoke CimMethod' complete."},
  {"time": "2018-12-14T15:26:23.256+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] 2018-12-14_15-26-23: Setting reports virtual directory on localhost\\MSSQLSERVER to ReportServer."},
  {"time": "2018-12-14T15:26:23.259+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Perform operation 'Invoke CimMethod' with following parameters, ''instance' = MSReportServer_ConfigurationSetting (InstanceName = \"MSSQLSERVER\"),'methodName' = SetVirtualDirectory,'namespaceName' = root/Microsoft/SQLServer/ReportServer/RS_MSSQLSERVER/v13/Admin'."},
  {"time": "2018-12-14T15:27:03.371+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Operation 'Invoke CimMethod' complete."},
  {"time": "2018-12-14T15:27:03.381+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] 2018-12-14_15-27-03: Adding reports URL reservation on localhost\\MSSQLSERVER: http://+:8888."},
  {"time": "2018-12-14T15:27:03.395+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Perform operation 'Invoke CimMethod' with following parameters, ''instance' = MSReportServer_ConfigurationSetting (InstanceName = \"MSSQLSERVER\"),'methodName' = ReserveUrl,'namespaceName' = root/Microsoft/SQLServer/ReportServer/RS_MSSQLSERVER/v13/Admin'."},
  {"time": "2018-12-14T15:27:08.437+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Operation 'Invoke CimMethod' complete."},
  {"time": "2018-12-14T15:27:08.438+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] 2018-12-14_15-27-08: Adding reports URL reservation on localhost\\MSSQLSERVER: https://hosting-test.elements.symplectic.org:443."},
  {"time": "2018-12-14T15:27:08.440+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Perform operation 'Invoke CimMethod' with following parameters, ''instance' = MSReportServer_ConfigurationSetting (InstanceName = \"MSSQLSERVER\"),'methodName' = ReserveUrl,'namespaceName' = root/Microsoft/SQLServer/ReportServer/RS_MSSQLSERVER/v13/Admin'."},
  {"time": "2018-12-14T15:27:13.992+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Operation 'Invoke CimMethod' complete."},
  {"time": "2018-12-14T15:27:13.994+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Perform operation 'Invoke CimMethod' with following parameters, ''instance' = MSReportServer_ConfigurationSetting (InstanceName = \"MSSQLSERVER\"),'methodName' = GenerateDatabaseCreationScript,'namespaceName' = root/Microsoft/SQLServer/ReportServer/RS_MSSQLSERVER/v13/Admin'."},
  {"time": "2018-12-14T15:27:14.910+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Operation 'Invoke CimMethod' complete."},
  {"time": "2018-12-14T15:27:15.024+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\\cimv2,'className' = Win32_Service'."},
  {"time": "2018-12-14T15:27:15.269+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Operation 'Enumerate CimInstances' complete."},
  {"time": "2018-12-14T15:27:15.270+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Perform operation 'Invoke CimMethod' with following parameters, ''instance' = MSReportServer_ConfigurationSetting (InstanceName = \"MSSQLSERVER\"),'methodName' = GenerateDatabaseRightsScript,'namespaceName' = root/Microsoft/SQLServer/ReportServer/RS_MSSQLSERVER/v13/Admin'."},
  {"time": "2018-12-14T15:27:15.289+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Operation 'Invoke CimMethod' complete."},
  {"time": "2018-12-14T15:27:15.371+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Preferred module SqlServer found."},
  {"time": "2018-12-14T15:27:15.375+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Importing PowerShell module 'SqlServer' with version '21.0.17240' from path 'C:\\Program Files\\WindowsPowerShell\\Modules\\SqlServer\\21.0.17240\\SqlServer.psm1'."},
  {"time": "2018-12-14T15:27:16.429+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'ReportServer'."},
  {"time": "2018-12-14T15:27:16.479+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'msdb'."},
  {"time": "2018-12-14T15:27:16.523+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'master'."},
  {"time": "2018-12-14T15:27:16.554+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'ReportServerTempDB'."},
  {"time": "2018-12-14T15:27:16.581+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'ReportServerTempDB'."},
  {"time": "2018-12-14T15:27:16.687+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'ReportServer'."},
  {"time": "2018-12-14T15:27:18.524+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'master'."},
  {"time": "2018-12-14T15:27:18.535+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'msdb'."},
  {"time": "2018-12-14T15:27:18.729+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'ReportServerTempDB'."},
  {"time": "2018-12-14T15:27:18.765+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'ReportServerTempDB'."},
  {"time": "2018-12-14T15:27:18.765+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'ReportServerTempDB'."},
  {"time": "2018-12-14T15:27:18.842+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'ReportServerTempDB'."},
  {"time": "2018-12-14T15:27:19.112+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Caution: Changing any part of an object name could break scripts and stored procedures."},
  {"time": "2018-12-14T15:27:19.207+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'ReportServerTempDB'."},
  {"time": "2018-12-14T15:27:19.306+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'ReportServer'."},
  {"time": "2018-12-14T15:27:19.309+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'ReportServer'."},
  {"time": "2018-12-14T15:27:19.390+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'ReportServer'."},
  {"time": "2018-12-14T15:27:19.645+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Caution: Changing any part of an object name could break scripts and stored procedures."},
  {"time": "2018-12-14T15:27:19.688+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'ReportServer'."},
  {"time": "2018-12-14T15:27:19.775+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'ReportServer'."},
  {"time": "2018-12-14T15:27:19.875+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'ReportServer'."},
  {"time": "2018-12-14T15:27:21.241+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] The module 'CreateRdlChunk' depends on the missing object 'CreateSegmentedChunk'. The module will still be created; however, it cannot run successfully until the object exists."},
  {"time": "2018-12-14T15:27:21.241+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] The module 'CreateRdlChunk' depends on the missing object 'CreateChunkSegment'. The module will still be created; however, it cannot run successfully until the object exists."},
  {"time": "2018-12-14T15:27:21.627+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'ReportServerTempDB'."},
  {"time": "2018-12-14T15:27:21.636+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'ReportServer'."},
  {"time": "2018-12-14T15:27:21.657+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'master'."},
  {"time": "2018-12-14T15:27:21.701+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'ReportServer'."},
  {"time": "2018-12-14T15:27:21.732+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'ReportServerTempDB'."},
  {"time": "2018-12-14T15:27:21.757+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'msdb'."},
  {"time": "2018-12-14T15:27:21.782+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'master'."},
  {"time": "2018-12-14T15:27:21.814+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Changed database context to 'ReportServer'."},
  {"time": "2018-12-14T15:27:21.816+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Perform operation 'Invoke CimMethod' with following parameters, ''instance' = MSReportServer_ConfigurationSetting (InstanceName = \"MSSQLSERVER\"),'methodName' = SetDatabaseConnection,'namespaceName' = root/Microsoft/SQLServer/ReportServer/RS_MSSQLSERVER/v13/Admin'."},
  {"time": "2018-12-14T15:27:28.863+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Operation 'Invoke CimMethod' complete."},
  {"time": "2018-12-14T15:27:28.866+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Perform operation 'Invoke CimMethod' with following parameters, ''instance' = MSReportServer_ConfigurationSetting (InstanceName = \"MSSQLSERVER\"),'methodName' = InitializeReportServer,'namespaceName' = root/Microsoft/SQLServer/ReportServer/RS_MSSQLSERVER/v13/Admin'."},
  {"time": "2018-12-14T15:27:29.008+00:00", "type": "verbose", "message": "[HOSTING-TEST]:                            [[SqlRS]SSRSConfig] Operation 'Invoke CimMethod' complete."},
  {"time": "2018-12-14T15:27:29.055+00:00", "type": "verbose", "message": "[HOSTING-TEST]: LCM:  [ End    Set      ]  [[SqlRS]SSRSConfig]  in 81.0980 seconds."},
  {"time": "2018-12-14T15:27:29.055+00:00", "type": "error", "message": "PowerShell DSC resource MSFT_SqlRS  failed to execute Set-TargetResource functionality with error message: Method InitializeReportServer() failed with an error. Error: The feature: \"Scale-out deployment\" is not supported in this edition of Reporting Services. (rsOperationNotSupported) (HRESULT:-2146233088) "},
```
It looks like the initialisation only partially fails - after this has run, Reporting Services Configuration Manager looks fine, but logging into the web GUI gets you a 503, until we manually restart the SSRS service.

After the restart, SSRS *seems* to be working fine, our custom roles/policies resources to their job, we can deploy reports, etc.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
I'll see if I can produce a minimal configuration to replicate this problem.

#### SQL Server edition and version the target node is running
```
Microsoft SQL Server 2016 (SP1-CU8) (KB4077064) - 13.0.4474.0 (X64)   Feb 24 2018 13:53:17   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

I'll see if I can find a Win2016+SQL2016 AMI that doesn't exhibit this problem.

#### SQL Server PowerShell modules present on the target node
```
Name         Version    Path                                                                                           
----         -------    ----                                                                                           
SqlServer    21.0.17240 C:\Program Files\WindowsPowerShell\Modules\SqlServer\21.0.17240\SqlServer.psd1                 
SqlServer    20.0       C:\Program Files\WindowsPowerShell\Modules\SqlServer\SqlServer.psd1                            
SQLASCMDLETS 2.0        C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\SQLASCMDLETS\SQLASC...
SQLPS        1.0        C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1      
```

#### The operating system the target node is running
```
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2608.amd64fre.rs1_release.181024-1742
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version and build of PowerShell the target node is running
```
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.14393.2608                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.14393.2608                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
```
Name         Version  Path                                                                              
----         -------  ----                                                                              
SqlServerDsc 12.1.0.0 C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\12.1.0.0\SqlServerDsc.psd1
```

### PR DESCRIPTION
**Pull request by bozho**
A fix for Reporting Services initialization on SQL Standard and lower editions

#### Pull Request (PR) description
An explicit call to `InitializeReportServer` CIM method is not needed when initialising Reporting Services, since the call to `SetDatabaseConnection` CIM method initialises it.

An explicit call to `InitializeReportServer` after `SetDatabaseConnection` on SQL Standard and lower editions fails since SSRS attempts to configure scale-out deployment, which is not supported on SQL Standard and lower editions.

#### This Pull Request (PR) fixes the following issues
- Fixes #1258 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1335)

### CODE REVIEW

**Comment by bozho** [comment]
@johlju I'm away next week, we'll sort out any outstanding issues the week after.

**Comment by kungfu71186** [comment]
@bozho, do you have a reference for this? 

I believe it's only initialized for 3 scenarios and it's only to create an asymmetric key

1. When database is first created (service starts for first time)
2. Node is added to scale out
3. When keys are recreated

Do you know if that's correct?

**Comment by bozho** [comment]
@kungfu71186 I have no reference, but your scenarios make sense. However, I don't think the resource currently supports either scaling out or recreating keys (if it did, we'd have to conditionally execute `InitializeReportServer` for scenarios 2 and 3)

**Comment by kungfu71186** [comment]
@bozho correct. I'm currently rewriting the entire resource, but was able to find what I needed. Definitely no small task :/

**Pull request merged**
