### PR TITLE
SqlAgentFailsafe: Adding resource to manage Agent Failsafe Operator

### PR DESCRIPTION
**Pull request by jpomfret**
#### Pull Request (PR) description
Adds the `SqlAgentFailsafe` resource, to allow you to manage adding a failsafe operator to the agent alert system, and choosing the notification:
image

#### This Pull Request (PR) fixes the following issues
None

#### Task list
- [X] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [X] Resource documentation added/updated in README.md.
- [X] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [X] Comment-based help added/updated.
- [X] Localization strings added/updated in all localization files as appropriate.
- [X] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1414)

### CODE REVIEW

**Comment by jpomfret** [comment]
Will take a look at those failed tests.

**Comment by johlju** [comment]
Awesome @jpomfret! Will look through this tomorrow.

**Comment by johlju** [comment]
Now it got blocked correctly. :) Waiting for code fixes 🙂

**Comment by johlju** [comment]
Just a small issue with the test after the recent change in the hashtable returned from Get function
https://ci.appveyor.com/project/PowerShell/sqlserverdsc/builds/26378864/job/egk2i0uwolsajpdp?fullLog=true#L3787

**Pull request merged**
