### PR TITLE
MSFT_SqlAgentOperator: Added resource for SQL Server Agent Operators

### PR DESCRIPTION
**Pull request by jpomfret**
#### Pull Request (PR) description
Added resource for Operators, can currently add an operator with an email address.

I've also added tests which I'm having some issues with, I have got the mock working for all but the throwing error pieces, I'm submitting this PR in the hope someone can point me in the right direction on that.

#### Task list
- [X] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [X] Resource documentation added/updated in README.md.
- [X] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [X] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [X] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1255)

### CODE REVIEW

**Comment by johlju** [comment]
@jpomfret Thank you for this PR. I have been busy with my day job so haven't been able to do reviews as much as I would have wanted. But slowly being able to get back into this. I will get to this PR as soon as possible.

**Comment by johlju** [comment]
Thanks for sending this in, sorry for not having review this until now. I will review this PR now, and see if I can see what's going on with the tests.

**Comment by jpomfret** [comment]
@johlju - I don't want this to go stale, I have reviewed all your changes. My issue is still with the tests. I have tried again to get the mocking to work for the drop operator but am struggling.

**Comment by mdaniou** [comment]
@jpomfret I feel your pain, this is the same for me.
I'll see if I can help you with that.

**Comment by mdaniou** [comment]
@jpomfret This is only a guess but you might want to have a look at the integration test **MSFT_SqlSetup.Integration.Tests.ps1**

**Line 170**, the Before All block defines the ResourceId that is used later on the It blocks 

`
        BeforeAll {
            $resourceId = "[$($script:DSCResourceFriendlyName)]Integration_Test"
        }`

**Line 249**
`            It 'Should have set the resource and all the parameters should match' {
                $resourceCurrentState = $script:currentConfiguration | Where-Object -FilterScript {
                    $_.ConfigurationName -eq $configurationName
                } | Where-Object -FilterScript {
                    $_.ResourceId -eq $resourceId
                }`

My guess is that somehow your It block in error returns 'Absent' because the wrong occurrence of the configuration is used.
Do you think that this could be your problem and inserting this logic would fix your integration test ?

**Comment by jpomfret** [comment]
@mdaniou - I don't actually have any integration tests written for this one, maybe I should. I was working on unit tests, I went back through them all today and believe I have them fixed. I'd mixed up the names of the operators so the mocking wasn't working correctly for them. Fingers crossed, thanks for your review!

**Comment by johlju** [comment]
@jpomfret I have a look now and see

**Comment by johlju** [comment]
@mdaniou could you please go into Reviewable and resolve your comments you made in this PR? If you see that they are resolved of course, otherwise re-comment on them.

**Comment by johlju** [comment]
@mdaniou Thank you so much for helping out reviewing! 😃

**Comment by johlju** [comment]
@jpomfret I made a really terrible mistake - I force pushed over you recent changes, I'm so sorry 😞  Please, can you force push your local repo `git push my SqlAgentOperator' so we get back to the current state you are in? 'my' is the remote name to your fork.

**Comment by johlju** [comment]
It should have been `git push my SqlAgentOperator --force'

**Comment by jpomfret** [comment]
No problem 😄. I just ran that and it looks like my latest changes (readme, and renaming the integration tests file) are in there.

**Comment by johlju** [comment]
@jpomfret Thank you 😌 🙇  This was one of those mistake you only do once and always remember 😄

**Comment by johlju** [comment]
Just some minor problems with test failing - when the tests are passing this is good to be merged!

**Comment by jpomfret** [comment]
I need to take a look at the `set` tests, they are throwing the wrong errors. I'll try and get back to it this afternoon (EST), thanks for your help.

**Comment by johlju** [comment]
Really awesome work on this!

**Comment by jpomfret** [comment]
Thanks @johlju for all your reviews and help!

**Comment by johlju** [comment]
Thank you! Hood to see you again in another PR. :smile:

**Pull request merged**
