### PR TITLE
SqlAGDatabase: Fix impersonate permission test

### LINKED ISSUE #1237: SqlAGDatabase: Impersonate permission incorrectly checked on SQL 2012
#### Details of the scenario you tried and the problem that is occurring
When running SqlAGDatabase with the MatchDatabaseOwner option Test-ImpersonatePermissions gets called. This dumps the fn_my_permissions for the user and checks for IMPERSONATE ANY LOGIN.

That permission does not exist on SQL 2012 and was only introduced in SQL 2014. This causes the test to fail even when equivalent permissions exist.

#### Verbose logs showing the problem
```
PowerShell DSC resource MSFT_SqlAGDatabase  failed to execute Set-TargetResource functionality with error message: The
login 'LAB\LocalAdministrator' is missing impersonate permissions in the instances 'DAC1N1, SEC1N2, DAC1N2, SEC1N3'.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : SEC1N1
```

#### Suggested solution to the issue
- Check for CONTROL SERVER permission. This is given directly or through sysadmin, and grants an implicit IMPERSONATE ANY LOGIN permission.
- Check for IMPERSONATE LOGIN permission for each database owner.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
                        SqlAGDatabase "AddDatabaseTo$($node.Role.AvailabilityGroup.Name)"
                        {
                            AvailabilityGroupName   = $node.Role.AvailabilityGroup.Name
                            BackupPath              = '\\CHDC1\Temp' # TODO: Remove this
                            DatabaseName            = "Dummy$($node.Role.AvailabilityGroup.Name)"
                            ServerName              = $node.NodeName
                            InstanceName            = $node.Role.SQLServer.InstanceName
                            Ensure                  = 'Present'
                            PsDscRunAsCredential    = $localAdministrator
                            MatchDatabaseOwner = $true # EXECUTE AS
                            DependsOn = '[WaitForAll]WaitForAllAGReplicas'
                        }
```

#### SQL Server edition and version the target node is running
SQL 2012

#### SQL Server PowerShell modules present on the target node
SqlServer, SQLPS

#### The operating system the target node is running
Windows Server 2012

#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

### PR DESCRIPTION
**Pull request by codykonior**
#### Pull Request (PR) description
When adding a database to an AG using SqlAGDatabase and the MatchDatabaseOwner switch, it checks for an IMPERSONATE ANY LOGIN permission.

That permission doesn't exist until SQL 2014. There are two other alternatives that exist on SQL Server 2012 (and also exist in higher versions):
- CONTROL SERVER (also granted as part of the sysadmin server role) permission
- IMPERSONATE <LoginName> permission

This PR adds checks for the two additional permissions if the IMPERSONATE ANY LOGIN permission doesn't exist. It also fixes code coverage for New-TerminatingError as I noticed that wasn't right.

I raised this [previously](https://github.com/PowerShell/SqlServerDsc/pull/1239) but the PR became too out of date to maintain. To address some of the comments of the time:

Re: SqlServerDscHelper.psm1 about $testLoginEffectPermissionsParams

> Could we actually call the existing helper function `Get-SqlInstanceMajorVersion` to know what the major version is and only call this if the version is 2014 or newer?"

The query that tests the permissions works fine even on lower versions so no change is necessary.

> We should not be using `$ServerObject.InstanceName`?

It's copy-paste of what was there previously.

ServiceName is not the service name. For default instances it's MSSQLSERVER where InstanceName is blank. For non-default instances both are the same.

Invoke-Query depends on InstanceName being MSSQLSERVER instead of blank so it has to stay as-is.

> Curious. Did the `MatchDatabaseOwner` parameter even work before since it never referenced the actual owner of the databases?

It would work in limited circumstances such as SQL 2014 and above, with IMPERSONATE ANY LOGIN permission (and possibly even more).

The reason I say "and possibly more" is that the RESTORE FULL is done under the impersonated account but then RESTORE LOG wasn't. This causes the process to fail even with the IMPERSONATE ANY LOGIN unless it has yet another another high level permission. This has all been fixed.

Re: Tests/Unit/SqlServerDSCHelper.Tests.ps1 about mocking

> If we instead mock the call to `Test-LoginEffectivePermissions` then we should be able to use a `ParameterFilter` on two different `Assert-MockCalled` to filter out that we actually call 'Impersonate..' and 'COntrol...' once each.
> I think mocking `Test-LoginEffectivePermissions` would also simplify this test, and give better control testing this helper function?

Test-LoginEffectivePermissions only gets called once, it then executes Invoke-Query one or more times to determine if the permissions are present; which is why that is mocked instead.

If I didn't do this and just mocked Test-LoginEffectivePermissions then nothing would change and my code wouldn't be covered by the test, and so PR would have reduced code coverage.

Re: Other comments about style and updating documentation.

I believe these are all done.

#### Further testing
I built a separate test rig to confirm this all works correctly on an actual instance. I ran it on my 5-node lab which can be built with my [OftenOn](https://codykonior.github.io/OftenOn) PowerShell module and the script executed in a PowerShell admin console on CHWK01 to reproduce.

This separate test is pretty huge and [in this gist so as not to clutter up the PR](https://gist.github.com/codykonior/4827e6158554b0a8e455109f82206ab4) but the final bit which is captured in the gif is easy enough to understand..

- Confirms SqlAGDatabase works on 2012 
- Confirms SqlAGDatabase fails on 2012 when MatchDatabaseOwner is used
- Confirms SqlAGDatabase gets restored on 2012 with the correct owner when MatchDatabaseOwner is used

It's checking the return bool from Invoke-DscResource and also who the owner is on the databases.

evidence

#### This Pull Request (PR) fixes the following issues
- Fixes #1237 

#### Task list
- [X] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [X] Resource documentation added/updated in README.md.
- [X] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [X] Comment-based help added/updated.
- [X] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1295)

### CODE REVIEW

**Comment by codykonior** [comment]
I can run the tests locally without issue and seemingly the code works with my separate test outside of the framework.

I haven't been able to find any remaining reason for the AppVeyor SqlAGDatabase tests to fail. I'll need some pointers on debugging it.

**Comment by johlju** [comment]
Can you please look at the failing tests
https://ci.appveyor.com/project/PowerShell/sqlserverdsc/builds/22691108/job/674q6197a3wkr9a7?fullLog=true#L615

**Comment by codykonior** [comment]
I don't know why those tests are failing. I had this problem locally until I fixed the TypeName in ConnectionContext (which is part of the change).

I wonder if AppVeyor is somehow stale. I'll try closing and re-opening the PR to trigger another rebuild.

**Comment by codykonior** [comment]
Any idea how I can investigate this further? I can't reproduce the failure locally.

**Comment by johlju** [comment]
You can debug in the appveyor build worker if you can’t reproduce it locally. See the AppVeyor documentation 
https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

**Comment by codykonior** [comment]
My update is that I still have yet to work out why this is happening or reproduce it locally. As a guess I believe it's related to the funny business in #239 and #774.

**Comment by codykonior** [comment]
I found the cause of the test failures. The Pester mock parameter filters fail because the Linux line endings on the build machine don't match the rest of PowerShell. It was never an issue before because each line of the existing code ended in a wildcard. By adding a line without a wildcard the mock would be skipped and try to connect to an actual server.

Anyway this is ready for review once the latest build passes.

**Comment by johlju** [comment]
@codykonior Can you double check the tests I commented on? It looks like the are the same? Otherwise it is all good now! 😄

**Comment by johlju** [comment]
@codykonior Awesome work on this! This one is merged now. 😄

**Pull request merged**
