### PR TITLE
Common Module - Improve Connect-SQL and Invoke-Query

### LINKED ISSUE #1354: Common Module: Connect-SQL verbose messaging
Verbose switch is enabled on the verbose message. I'd prefer if verbose wasn't forced
Yes:
`write-verbose 'Message'`

No:
`write-verbose 'Message' -Verbose`

### LINKED ISSUE #1355: Common Resource: Invoke-Query
It doesn't appear there is way to pass in all the same parameters as connect-sql. So if I wanted to connect using sql credentials or windows, I wouldn't be able to that with invoke-query

 `$serverObject = Connect-SQL -ServerName $SQLServer -InstanceName $SQLInstanceName`

Also the parameters differ from Connect-SQL, can we create alias ServerName and InstanceName of Invoke-Query

### PR DESCRIPTION
**Pull request by kungfu71186**
Non-breaking changes
- Fixes #1354
- Fixes #1355 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1356)

### CODE REVIEW

**Comment by kungfu71186** [comment]
@johlju may need help on unit tests here, not sure how to emulate the 'Microsoft.SqlServer.Management.Smo.Server' to test that out.

**Comment by johlju** [comment]
In the phone now so can’t give you a good example, but there are stubs for the SMO object model written I C#. See here how to load them. 

https://github.com/PowerShell/SqlServerDsc/blob/a7add04577baa0b9150e1991bc65cadc0fdbf707/Tests/Unit/MSFT_SqlAGListener.Tests.ps1#L43

You can extend the stubs with other properties and methods as needed. They are only minimal of what is needed by the current unit tests.

**Comment by kungfu71186** [comment]
@johlju Ready for review. I put verbose back in for now, until i can further investigate this issue.

**Comment by kungfu71186** [comment]
@johlju Finally got the test cases to work. Ready for review.

**Comment by kungfu71186** [comment]
@johlju 

I rewrote the connect-sql to make it a bit more clear.

Found a few issues in test i think:
https://github.com/kungfu71186/SqlServerDsc/blob/85f2d104d2aec5c60062b827820727e745920098/Tests/Unit/DscResource.Common.Tests.ps1#L2342
Not sure how it's going to use windows credentials here, since no credentials are specified, so it actually uses integrated security.

https://github.com/kungfu71186/SqlServerDsc/blob/85f2d104d2aec5c60062b827820727e745920098/Tests/Unit/DscResource.Common.Tests.ps1#L2438
No idea what this test is trying to do. Not sure how you get an instance back that you didn't specify. But in any case, I updated that test to check if you can't connect. Otherwise, let me know what that unit test was trying to test for.

The rewrite adds a new type:
```
        [Parameter()]
        [ValidateSet('Integrated', 'WindowsUser', 'SqlLogin')]
        [System.String]
        $LoginType = 'Integrated'
```

But the only to check for credential is to do dynamic parameter i believe. If it's not integrated, then we need a credential and it's mandatory.

Let me know what you think about that. I can update invoke-query to do that as well.

Last thing, should we really have 2 query functions? I didn't notice we had invoke-sqlscript and invoke-query. Shouldn't we just combine these? We can leave one or the other for backward compatibility and then just call one with the other. What do you think?

**Comment by johlju** [comment]
I hope I answered all questions, let me know if something I says seems odd. Hard to keep track on the changes in all PR's 😄

**Comment by kungfu71186** [comment]
@johlju yeah no problem. Makes sense. I haven't committed my changes yet since it takes 40 minutes to do tests, but wanted to hear your thoughts first. I updated the code to hopefully make it more clear. 

I'm also trying to not use a bunch of if statements when not needed, so hopefully a few changes I made makes it a bit easier to read. 

I'll make those same changes to invoke as well and then commit them. This PR is for both connect and invoke.

On mobile, so can't quote.
"It is testing that it is possible to connect with current credentials, it should be possible to do this, like you mentioned in a comment"

But what I mean by that test case is that credentials is not specified, so it actually uses integrated creds, even though Windows is specified, it actually doesn't do anything in this case

**Comment by kungfu71186** [comment]
@johlju I'm sticking to my guns on Integrated lol. We are saying the same thing, but our terminology is different i believe. Please see comments for what I mean.

**Comment by kungfu71186** [comment]
@johlju I just did some quick research on this. There is one problem. I need to investigate a few things, but one thing I do know, is that connect should NOT be used without a disconnect. 

There may be a few options here, but I'll know more after I investigate a few things. But this is good, because now I know connect shouldn't have been used without a disconnect, otherwise it leaves a connection open.

**Comment by johlju** [comment]
Hmm. I thought it closed when the PS session ended? Although, not sure how long the LCM keep the same session. Does the connection stay open even when a session closes? Then it’s not good. That can have a bad impact. :/

**Comment by kungfu71186** [comment]
@johlju I just ran some tests. Connect is the safer option. You can disconnect and pass the object around like normal. It will run in 'Server' mode after that. I'll check the sessions, but it should be fine to disconnect with no impact. Just verified, closing the powershell session closes the sql session too.

https://docs.microsoft.com/en-us/sql/relational-databases/server-management-objects-smo/create-program/connecting-to-an-instance-of-sql-server?view=sql-server-2017

`You can create an instance of the Server object and establish a connection to the instance of SQL Server in three ways. The first is using a ServerConnection object variable to provide the connection information. The second is to provide the connection information by explicitly setting the Server object properties. The third is to pass the name of the SQL Server instance in the Server object constructor.`

https://docs.microsoft.com/en-us/sql/relational-databases/server-management-objects-smo/create-program/disconnecting-from-an-instance-of-sql-server?view=sql-server-2017

`When the Connect method is called, the connection is not automatically released. The Disconnect method must be called explicitly to release the connection to the connection pool. Also, you can request a non-pooled connection. You do this by setting the NonPooledConnection property of the ConnectionContext property that references the ServerConnection object.`


It's good for when you need to run a bunch of things in the same session and then close it.

I think the best thing is try catch with finally to close the session. This will verify that you can actually connect. Checking status basically does the same thing as well, but returns it's status. Depending on the status of the server though, you may not be able to run queries, but you can connect. 

No matter what the situation is, you need a try catch and then check the status in there if you wanted, but i feel like it's not needed.

**Comment by johlju** [comment]
Look's good, I just need a rebase so you can move the change log entries back under the unreleased section after the recent release. 🙂

**Comment by johlju** [comment]
@kungfu71186 Could you please rebase this one again?

**Comment by johlju** [comment]
@kungfu71186 I'm happy to extend the `Invoke-Query` with the suggested changes in this PR. The Connect-SQL changes are already merged through another PR (and I credited you for those changes). Either rebase this PR or send in a new PR with those changes. 🙂

**Comment by kungfu71186** [comment]
@johlju I'll probably do another PR. Be easier. Hopefully get to it in the morning.

**Pull request closed without merging**
