### PR TITLE
SqlServerMemory: Fix so auto memory on Azure VMs is reported correctly

### LINKED ISSUE #914: SqlServerMemory: Auto memory on Azure VMs is off by an order of magnitude on large VMs
**Details of the scenario you tried and the problem that is occurring:**
Provision an Azure VM of type:  Standard_E32_v3   VM (Windows) (with 256GB RAM) and have xSQLServerMemory  automatically set max memory.
Expected would be that it sets SQL Server max memory to about 200+ GB RAM, actual result: it sets to about 27GB RAM.

The reason for that is that the script uses 
`((Get-CimInstance -ClassName Win32_PhysicalMemory).Capacity | Measure-Object -Sum).Sum`
to get the total amount of RAM. On Azure, on that VM size that is around 30~ GB RAM.

A more correct way of getting the total amount of memory available would be:
`(Get-Ciminstance Win32_OperatingSystem).TotalVisibleMemorySize`
(to note - the result here is in KB, vs Bytes as with Win32_PhysicalMemory.Capacity)

**The DSC configuration that is using the resource (as detailed as possible):**
```
        xSQLServerMemory Set_SQLServerMaxMemory_ToAuto
        {
            Ensure = 'Present'
            DynamicAlloc = $true
            SQLInstanceName = $SQLInstanceName
        }
```
**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Windows Server 2016, PS 5.0

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
SQL Server 2016 SP1

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
xSqlServer 7.1 - but this reproes on all version after that as well

### PR DESCRIPTION
**Pull request by ejleroy**
Updated Cim Class to Win32_ComputerSystem (instead of Win32_PhysicalMemory) because the correct memory size was not being detected correctly on Azure VMs

Fixes #914

#### Task list

- [x] Added an entry under the Unreleased section in the CHANGELOG.md? Entry
      should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md?
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help?
- [ ] Comment-based help added/updated?
- [ ] Localization strings added/updated in all localization files as appropriate?
- [ ] Examples appropriately added/updated?
- [ ] Unit tests added/updated?
      See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible)?
      See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to
      [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)
      and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md)?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1154)

### CODE REVIEW

**Comment by johlju** [comment]
@ejleroy Many thanks for your contribution and fixing this issue! 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @ejleroy)

---

*[a discussion](https://reviewable.io/reviews/powershell/sqlserverdsc/1154#-LG4_ow50T5zqfK05R28:-LG4_ow50T5zqfK05R29:blfoo4v) (no related file):*
The tests are failing could you please look at resolving those? I can't merge until the tests are passing. Thanks!
https://ci.appveyor.com/project/PowerShell/sqlserverdsc/build/9.0.369.0?fullLog=true#L4470

---

*[a discussion](https://reviewable.io/reviews/powershell/sqlserverdsc/1154#-LG4_tgM0TjTT7DUoTfz:-LG4_tgM0TjTT7DUoTg-:b-6bt7c2) (no related file):*
Could you please add an descriptive entry, for each change/issue, to the Unreleased section of the change log in the file README.md? If an entry resolves an issue please reference the issue where applicable. You may suffix (it's optional) each entry with your name. Example of the format for the entry.
```
* Descriptive entry ([issue #123](https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/123). [Name/Alias (@github_account)](https://github.com/github_account)
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1154#-:-LG4_h0F3NeA3X1mCLMS:b-xrs4p9)*

**Comment by johlju** [comment]
@ejleroy FYI. This particular problem in the tests is not caused by this PR 🤔 I will open a new issue for this.
https://ci.appveyor.com/project/PowerShell/sqlserverdsc/build/9.0.369.0?fullLog=true#L7771

**Comment by ejleroy** [comment]
@johlju  Added the below changes to the CHANGELOG.md in unreleased section

- Changes to SqlServerMemory
  - Using Get-CimInstance -ClassName Win32_ComputerSystem).TotalPhysicalMemory 
    ([issue #1154](https://github.com/PowerShell/SqlServerDsc/issues/1154))

**Comment by johlju** [comment]
For me to be able to merge this change, then please

* Sign the CLA (see comment above).
* Rebase the PR to get the latest changes (I merged a fix for one of the failing tests that is not part of your code change).
* Resolve the failing tests; https://ci.appveyor.com/project/PowerShell/sqlserverdsc/build/9.0.372.0?fullLog=true#L4469

There are merge conflicts since your PR was not based on the latest changes. Could you please rebase against branch dev using `git rebase` (not by using `git pull` or `git merge`, to keep the commit history). If you don't know how to rebase your local dev and working branch, please look at how to [Resolve merge conflicts](https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts).
Let me know if you need any assistance.

**Comment by ejleroy** [comment]
@johlju Rebased and recommitted the fix.  Test just kicked off and waiting for success.

**Comment by johlju** [comment]
Please resolve the failing tests here https://ci.appveyor.com/project/PowerShell/sqlserverdsc/build/9.0.373.0?fullLog=true#L4510 and here https://ci.appveyor.com/project/PowerShell/sqlserverdsc/build/9.0.373.0?fullLog=true#L1684

**Comment by johlju** [comment]
Closing this PR as it has been opened a new PR.

**Pull request closed without merging**
