### PR TITLE
SqlSetup: Clearly document and validate SecurityMode Parameter

### LINKED ISSUE #1010: SqlSetup: SecurityMode parameter is not clear how to use
**Details of the scenario you tried and the problem that is occurring:**
The parameter `SecurityMode` is not clear how to use. It does not say that the only supported value is 'SQL', neither is it using a validate set so this can be set to anything, without throwing. 

Parameter description should also be update to mention that the parameter enables mixed mode authentication in SQL Server.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by TraGicCode**
**Pull Request (PR) description**
Clearly document and validate SecurityMode Parameter.

**This Pull Request (PR) fixes the following issues:**
Fixes #1010 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1058)

### CODE REVIEW

**Comment by johlju** [comment]
Thanks so much for fixing this issue and updating the documentation! :smile: 
Just a few review comments.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[README.md, line 1516 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1058#-L6kAO1whHHjAEQM-JNy:-L6kAO1whHHjAEQM-JNz:b-67vv01) ([raw file](https://github.com/powershell/sqlserverdsc/blob/8ddbd222e0e60fdc77dc0aa21246e896f8817a07/README.md#L1516)):*
> ```Markdown
> * **`[String[]]` SQLSysAdminAccounts** _(Write)_: Array of accounts to be made SQL
>   administrators.
> * **`[String]` SecurityMode** _(Write)_: Security mode to apply to the SQL Server instance. 'SQL' indicates mixed-mode authentication while 'Windows' indicates windows authentication.
> ```

Maybe we should add that 'If this parameter is not set it will default to use Windows authentication.'.  Add that to schema.mof and comment-based help as well.

---

*[README.md, line 1516 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1058#-L6kBFHo3LxHCZQ4yJm0:-L6kBFHo3LxHCZQ4yJm1:b4s7b8g) ([raw file](https://github.com/powershell/sqlserverdsc/blob/8ddbd222e0e60fdc77dc0aa21246e896f8817a07/README.md#L1516)):*
> windows authentication

I think this should be written as 'Windows authentication' (upper 'W') since it's a name? Throughout.

---

*[README.md, line 1516 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1058#-L6kBYKrIuC16OKHVNJM:-L6kBYKrIuC16OKHVNJN:b-thmib2) ([raw file](https://github.com/powershell/sqlserverdsc/blob/8ddbd222e0e60fdc77dc0aa21246e896f8817a07/README.md#L1516)):*
> ```Markdown
> * **`[String[]]` SQLSysAdminAccounts** _(Write)_: Array of accounts to be made SQL
>   administrators.
> * **`[String]` SecurityMode** _(Write)_: Security mode to apply to the SQL Server instance. 'SQL' indicates mixed-mode authentication while 'Windows' indicates windows authentication.
> ```

In the README.md (only) we also add list of possible values `{ *Windows* | SQL }` to the end of the description (after full stop '.'). See for example parameter descriptions in SqlAg for reference. 

---

*[DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.schema.mof, line 26 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1058#-L6kAijF04OW8Erm1mfV:-L6kAijF04OW8Erm1mfW:b-9yq790) ([raw file](https://github.com/powershell/sqlserverdsc/blob/8ddbd222e0e60fdc77dc0aa21246e896f8817a07/DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.schema.mof#L26)):*
> ```
>     [Write, Description("Collation for SQL.")] String SQLCollation;
>     [Write, Description("Array of accounts to be made SQL administrators.")] String SQLSysAdminAccounts[];
>     [Write, Description("Security mode to apply to the SQL Server instance.")], ValueMap{"SQL", "Windows"}, Values{"SQL", "Windows"}] String SecurityMode;
> ```

Please update the description here to the same as in the README.md and schema.mof.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1058#-:-L6kBxsdRgcKkLV6-34a:b-555t9e)*

**Comment by TraGicCode** [comment]
*[README.md, line 1516 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1058#-L6kAO1whHHjAEQM-JNy:-L6oJjcvFq_TRd14BPCB:b-nlsi1m) ([raw file](https://github.com/powershell/sqlserverdsc/blob/8ddbd222e0e60fdc77dc0aa21246e896f8817a07/README.md#L1516)):*
> { *Windows* | SQL }
I went ahead and put 'Default is Windows' instead to be consistent with the other documentation for other resources.  Is this fine?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1058)*

**Comment by TraGicCode** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[README.md, line 1516 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1058#-L6kBYKrIuC16OKHVNJM:-L6oK5naEwblxtfX_nbv:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/8ddbd222e0e60fdc77dc0aa21246e896f8817a07/README.md#L1516)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

In the README.md (only) we also add list of possible values `{ *Windows* | SQL }` to the end of the description (after full stop '.'). See for example parameter descriptions in SqlAg for reference. 
</blockquote></details>

Done.

---

*[README.md, line 1516 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1058#-L6kBFHo3LxHCZQ4yJm0:-L6oK6LJQ1ZHRko4bAqU:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/8ddbd222e0e60fdc77dc0aa21246e896f8817a07/README.md#L1516)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> windows authentication

I think this should be written as 'Windows authentication' (upper 'W') since it's a name? Throughout.
</blockquote></details>

Done.

---

*[README.md, line 1516 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1058#-L6kAO1whHHjAEQM-JNy:-L6oK8L3eRzG_jzlnxI7:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/8ddbd222e0e60fdc77dc0aa21246e896f8817a07/README.md#L1516)):*
<details><summary><i>Previously, TraGicCode (Michael Fyffe) wrote…</i></summary><blockquote>

> { *Windows* | SQL }
I went ahead and put 'Default is Windows' instead to be consistent with the other documentation for other resources.  Is this fine?
</blockquote></details>

Done.

---

*[DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.schema.mof, line 26 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1058#-L6kAijF04OW8Erm1mfV:-L6oK4mtXi2WQ4-72R82:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/8ddbd222e0e60fdc77dc0aa21246e896f8817a07/DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.schema.mof#L26)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please update the description here to the same as in the README.md and schema.mof.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1058)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1058#-:-L6opo4Q6cO7bfFPef9I:bnfp4nl)*

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.schema.mof, line 26 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1058#-L6oqmxhytmfjQcfcRPS:-L6oqmxhytmfjQcfcRPT:b9ugy95) ([raw file](https://github.com/powershell/sqlserverdsc/blob/663aefdf168057d4318f3b8825c22026aa0b9ba6/DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.schema.mof#L26)):*
> Windows.")]

I was to quick to hit LGTM and didn't check that the test was failing. There is a ']' to much here I think. The one directly after the description should not be there?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1058)*

**Comment by TraGicCode** [comment]
*[DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.schema.mof, line 26 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1058#-L6oqmxhytmfjQcfcRPS:-L6qBwsIbSM1QgtoOPYY:b89guov) ([raw file](https://github.com/powershell/sqlserverdsc/blob/663aefdf168057d4318f3b8825c22026aa0b9ba6/DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.schema.mof#L26)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Windows.")]

I was to quick to hit LGTM and didn't check that the test was failing. There is a ']' to much here I think. The one directly after the description should not be there?
</blockquote></details>

Good catch.  Good thing you didn't merge this in yet! :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1058)*

**Comment by TraGicCode** [comment]
*[DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.schema.mof, line 26 at r2](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1058#-L6oqmxhytmfjQcfcRPS:-L6qCogvoT-SCe1c-RC8:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/663aefdf168057d4318f3b8825c22026aa0b9ba6/DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.schema.mof#L26)):*
<details><summary><i>Previously, TraGicCode (Michael Fyffe) wrote…</i></summary><blockquote>

Good catch.  Good thing you didn't merge this in yet! :+1: 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1058)*

**Comment by TraGicCode** [comment]
Hmm, There is 1 failed test but i cannot find the failure in the appveyor logs.  Is my change still wrong?

**Comment by johlju** [comment]
That change is all good, now there seem to be an error in one markdown file
https://ci.appveyor.com/project/PowerShell/sqlserverdsc/build/9.0.221.0/tests

Download the full log from the console view and see if you can see which file it complains about.

**Comment by TraGicCode** [comment]
@johlju Not sure if i did this in an acceptable fashion.  I had line too long markdown linting errors.  In order to solve these i essentially places some newlines in.

**Comment by johlju** [comment]
You did it correctly. Looking good, markdown is formatted correctly when I view the final markdown file.

**Comment by johlju** [comment]
:lgtm:

Truly this time :smile: 

---

Reviewed 1 of 1 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1058#-:-L6vWfiola_Vr9MXPG68:b-bdes0e)*

**Comment by johlju** [comment]
@TraGicCode Thanks again for this! Great work!

**Pull request merged**
