### PR TITLE
SqlServerDsc: Fix CHANGELOG.md after resource module rename

### LINKED ISSUE #916: BREAKING CHANGE: SqlServerDsc: The resource module has been renamed
**Details of the scenario you tried and the problem that is occurring:**
The resource module has been renamed to SqlServerDsc. We should reflect that in the CHANGELOG.md

It was rename as part of issue #851. When that major breaking change was done we took the opportunity to rename the resource module as well.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by johlju**
**Pull Request (PR) description**
- BREAKING CHANGE: Resource module has been renamed to SqlServerDsc (issue #916).

**This Pull Request (PR) fixes the following issues:**
Fixes #916 

**Task list:**

- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/919)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/919)*

**Comment by johlju** [comment]
:LGTM:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/919#-:-L-3IfdD5L7G-8W0l59t:bmxilld)*

**Comment by randomnote1** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[CHANGELOG.md, line 6 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/919#-L-7NQahJ_I7DsDPB1Xz:-L-7NQahJ_I7DsDPB1Y-:b-vz81v2) ([raw file](https://github.com/powershell/sqlserverdsc/blob/09da6cd4458be832d6735315df85967a9ded2498/CHANGELOG.md#L6)):*
> ```Markdown
> 
> - BREAKING CHANGE: Resource module has been renamed to SqlServerDsc
>   ([issue #916](https://github.com/PowerShell/xSQLServer/issues/916)).
> ```

This should be `https://github.com/PowerShell/SqlServerDsc/issues/916` I think. It appears the link still works though.

---

*[CHANGELOG.md, line 8 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/919#-L-7Nhf7cPUiE0QjAOcW:-L-7Nhf7cPUiE0QjAOcX:b8s2uh7) ([raw file](https://github.com/powershell/sqlserverdsc/blob/09da6cd4458be832d6735315df85967a9ded2498/CHANGELOG.md#L8)):*
> xSQLServer
This should be SqlServerDsc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/919)*

**Comment by johlju** [comment]
Thanks for catching that! Copy paste error :/

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 6 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/919#-L-7NQahJ_I7DsDPB1Xz:-L-7jJaZ5Ij7iyQ7ydRr:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/09da6cd4458be832d6735315df85967a9ded2498/CHANGELOG.md#L6)):*
<details><summary><i>Previously, randomnote1 (Dan Reist) wrote…</i></summary><blockquote>

This should be `https://github.com/PowerShell/SqlServerDsc/issues/916` I think. It appears the link still works though.
</blockquote></details>

Done.

---

*[CHANGELOG.md, line 8 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/919#-L-7Nhf7cPUiE0QjAOcW:-L-7jKHNyNZnmoj1ru8X:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/09da6cd4458be832d6735315df85967a9ded2498/CHANGELOG.md#L8)):*
<details><summary><i>Previously, randomnote1 (Dan Reist) wrote…</i></summary><blockquote>

> xSQLServer
This should be SqlServerDsc
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/919#-:-L-7jM7ELTPig8L6fjaB:b-4yfbrl)*

**Comment by randomnote1** [comment]
Sure thing!
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/919#-:-L-7kBXS5RqOLFGMtICx:b1ucogz)*

**Pull request merged**
