### PR TITLE
New Resource SqlServerSecureConnection

### PR DESCRIPTION
**Pull request by mcollera**
#### Pull Request (PR) description
Additional resource to setup an encryptedconnection in SQL

#### This Pull Request (PR) fixes the following issues
None

#### Task list

- [x] Resource documentation added/updated in README.md.
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1212)

### CODE REVIEW

**Comment by johlju** [comment]
@mcollera I'm gonna merge 3 other PR's today, I suggest you wait to rebase until those are merged, to minimize the times you need to rebase. 🙂

**Comment by johlju** [comment]
This is how it looks on the AppVeyor build worker (when [RDP into it](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/)).

image

So I guess the FQDN is `$env:COMPUTERNAME` for the AppVeyor build worker? Will that work?

The first item in the list of the property `SuffixSearchList` is the primary DNS suffix, if configured. So for the build worker it is not configured, but we could the first item if it is not `$null` and suffix that to the computer name, so it will work in another test environment, with an actual domain?

Running this
```
New-SelfSignedCertificate -DnsName $env:COMPUTERNAME, $env:COMPUTERNAME -CertStoreLocation "cert:\LocalMachine\My"
```

Gives 

image

image

That we could run [Export-PfxCertificate](https://docs.microsoft.com/en-us/powershell/module/pkiclient/export-pfxcertificate?view=win10-ps) on, and then [Import-PfxCertificate](https://docs.microsoft.com/en-us/powershell/module/pkiclient/import-pfxcertificate?view=win10-ps) into the trusted store? 

If you think this can work, then it would be great to get an integration test. But you have the best knowledge of this, I guess the FQDN part is the most difficult.

**Comment by johlju** [comment]
Tested this code manual on the build worker. Got a few gotchas. I think it will be very good if we can test this in an integration test.
*Also test with another resource so they can work together, connect with encryption enabled. If they don't then we must add a backlog issues to get that support.*

Installed the certificate into the personal store, and imported into the root store. 

```
PS > New-SelfSignedCertificate -DnsName $env:COMPUTERNAME, $env:COMPUTERNAME -CertStoreLocation "cert:\LocalMachine\My"


   PSParentPath: Microsoft.PowerShell.Security\Certificate::LocalMachine\My

Thumbprint                                Subject
----------                                -------
5FD0BF853C5BB369A1227211A43E7C094AA648A8  CN=APPVYR-WIN

PS > $mypwd = ConvertTo-SecureString -String "1234" -Force -AsPlainText
PS > Get-ChildItem -Path cert:\localMachine\my\5FD0BF853C5BB369A1227211A43E7C094AA648A8 | Export-PfxCertificate -FilePath C:\mypfx.pfx -Password $mypwd
PS > Import-PfxCertificate -FilePath C:\mypfx.pfx -CertStoreLocation Cert:\LocalMachine\Root -Password $mypwd

   PSParentPath: Microsoft.PowerShell.Security\Certificate::LocalMachine\Root

Thumbprint                                Subject
----------                                -------
5FD0BF853C5BB369A1227211A43E7C094AA648A8  CN=APPVYR-WIN
```

After that integration tests for SqlSetup ran finiished (made a stripped down debug branch for testing), I manually ran this
```powershell
Set-TargetResource -InstanceName DSCSQL2016 -Thumbprint 5FD0BF853C5BB369A1227211A43E7C094AA648A8 -ForceEncryption $true -Ensure Present -ServiceAccount "svc-SqlPrimary"
# Maybe it should be
# -ServiceAccount "$($env:COMPUTERNAME)\svc-SqlPrimary"
# but tested with the above.
```

When debugging row by row, it first failed on this

```
            $superSocketNetLib.SetValue('Certificate', $Thumbprint)
            $superSocketNetLib.SetValue('ForceEncryption', [int]$ForceEncryption)
```

with the errors

```
Exception calling "SetValue" with "2" argument(s): "Cannot write to the registry key."
At C:\Users\appveyor\Desktop\Untitled1.ps1:296 char:13
+             $superSocketNetLib.SetValue('Certificate', $Thumbprint)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : UnauthorizedAccessException
 
[DBG]: PS C:\Users\appveyor>> 
Exception calling "SetValue" with "2" argument(s): "Cannot write to the registry key."
At C:\Users\appveyor\Desktop\Untitled1.ps1:297 char:13
+             $superSocketNetLib.SetValue('ForceEncryption', [int]$Forc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : UnauthorizedAccessException
```

I went in an set the values manually in the registry to continue testing.
It went in to `Set-CertificatePermission`, but here the `$cert.PrivateKey.CspKeyContainerInfo.UniqueKeyContainerName` doesn't return a value, so the path end up wrong, but the permission is set on the root folder, and then the `Test-CertificatePermission` will return `$true` since it also look at the wrong path.

```
[DBG]: PS C:\Users\appveyor>> $keyName = $cert.PrivateKey.CspKeyContainerInfo.UniqueKeyContainerName

[DBG]: PS C:\Users\appveyor>> $keyFullPath = $keyPath + $keyName

[DBG]: PS C:\Users\appveyor>> $keyFullPath
C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys\
```

I continued, but then it failed on
```
Restart-SqlService -SQLServer localhost -SQLInstanceName $InstanceName
```
**This error is most likely because the 'appveyor' account wasn't allowed to connect.**
```
VERBOSE: Found PowerShell module Sqlps already imported in the session.
System.InvalidOperationException: Failed to connect to SQL instance 'localhost\DSCSQL2016'.
At C:\projects\sqlserverdsc\DscResources\CommonResourceHelper.psm1:89 char:5
+     throw $errorRecordToThrow
+     ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], Exception
    + FullyQualifiedErrorId : MachineStateIncorrect
```

After this I tried to manually restart the SQL Server service. But it failed to start. So I went into the `Manage Private Keys` on the certificate in `certlm.msc`, and added the account for read on the primary key.

image

After that I could start the service again. 

The appveyor build worker terminates after 60 minutes so couldn't test to connect with an accurate account to the instance after the certificate was in place.

**Comment by johlju** [comment]
I see these issues

* The `$superSocketNetLib.SetValue()` give errors.
* The `$cert.PrivateKey.CspKeyContainerInfo.UniqueKeyContainerName` doesn't return a value for all accepted certificates (?).
* Restart-SqlServer should be able to connect to the instance when force encryption is enabled. *Maybe this do work already.*

**Comment by mcollera** [comment]
What account are you logged in with? And are you running elevated? I wonder if it’s a permission issue I’m powershell

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by johlju** [comment]
I think the AppVeyor build worker is always running elevated, but not certain now. If you think it’s a permission error, then it will work when the new integration test runs.

**Comment by mcollera** [comment]
Yeah because then it will run as system. I think it is just because you were able to set everything manually when logged in.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by johlju** [comment]
I was logged in with the default account “appveyor”. 

You can test this manually your self too. You can connect your fork to AppVeyor (it’s free), and then when you push branches to your fork you can see the test runs. You can add settings in the AppVeyor.yml file that says it should enable RDP and it will give you the username and password. See link in previous comment how to enable it.  Important to use the “on_finished” so it breaks when the test run is done (and not terminate the build worked directly).

**Comment by johlju** [comment]
Yes precisely, it will run as system by default. But it can also be run using PsDscRunAsCredential, running it as a user, so if that is a problem then a requirement will be that it must run as system. But it should be able to be run as a local admin user too right?

**Comment by mcollera** [comment]
Yes it should. And dsc will be elevated.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by johlju** [comment]
Then it just probably the certificate problem, that it didn’t have a RSA private key on disk. It should support all accepted certificates.

**Comment by mcollera** [comment]
You have to have a private key though for this to work.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by johlju** [comment]
But it has a private key on the certificate in the cert store. That isn't enough? See screen shot on the certificate, and I manually added permission to the private key (in the cert store) for the SQL Server service account to access it. Then the service started correctly. It did not start when the permission was not there.

**Comment by johlju** [comment]
I run the tests again, and by default the 'appveyor' account is elevated, but run with 'Run as administrator' anyway just in case, and the 'appveyor' account is local admin. Still fails.

image

**Comment by mcollera** [comment]
Is it possible for me to remote in?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by johlju** [comment]
Sure, the RPD information is in line 7; https://ci.appveyor.com/project/johlju/sqlserverdsc?fullLog=true

30 minutes left, after that the build worker terminates.

**Comment by johlju** [comment]
I have not forgotten about this one, but haven't had time to get back to this yet. Hopefully tomorrow. 🙂

**Comment by johlju** [comment]
@mcollera Just want to say that I think you do an awesome job with this new resource! 😃

**Comment by johlju** [comment]
@mcollera This is now merged. Thank you for your awesome work on this one! 😃

**Comment by johlju** [comment]
@mcollera I missed (again) that the entry in the CHANGELOG.md merged into the wrong place (because of the last release that modified the change log). I will fix it in the PR #1221.

**Pull request merged**
