### PR TITLE
SqlAG/SqlAGDatabase/SqlAGReplica - Updating examples to include enable HADR option

### LINKED ISSUE #1182: MSFT_SqlAGReplica  failed to execute Set-TargetResource functionality with error message: HADR is not enabled
SqlServerLogin AddNTServiceClusSvc
        {
            Ensure               = 'Present'
            Name                 = 'NT SERVICE\ClusSvc'
            LoginType            = 'WindowsUser'
            ServerName           = $SqlNode
            InstanceName         = "MSSQLSERVER"
            PsDscRunAsCredential = $SqlInstallCredential
        }

        # Add the required permissions to the cluster service login
        SqlServerPermission AddNTServiceClusSvcPermissions
        {
            DependsOn            = '[SqlServerLogin]AddNTServiceClusSvc'
            Ensure               = 'Present'
            ServerName           = $SqlNode
            InstanceName         = "MSSQLSERVER"
            Principal            = 'NT SERVICE\ClusSvc'
            Permission           = 'AlterAnyAvailabilityGroup', 'ViewServerState'
            PsDscRunAsCredential = $SqlInstallCredential
        }

        SqlServerEndpoint HADREndpoint
        {
            EndPointName         = 'HADR'
            Ensure               = 'Present'
            Port                 = $portNumber
            ServerName           = $SqlNode
            InstanceName         = "MSSQLSERVER"
            PsDscRunAsCredential = $SqlInstallCredential
        }
  SqlAGReplica AddReplica
        {
            Ensure                     = 'Present'
            Name                       = $SqlNode
            AvailabilityGroupName      = $avgGroupName
            ServerName                 = $SqlNode
            InstanceName               = "MSSQLSERVER"
            PrimaryReplicaServerName   = $SqlPrimaryReplicaNode
            PrimaryReplicaInstanceName = "MSSQLSERVER"  
            PsDscRunAsCredential       = $SqlInstallCredential
            DependsOn                  = '[SqlSetup]InstallDefaultInstance'            
        }

### PR DESCRIPTION
**Pull request by wsmelton**
#### Pull Request (PR) description
Updating examples to include enabling the HADR option for SQL Server.

#### This Pull Request (PR) fixes the following issues
Fixes #1182 

#### Task list

- [x] Added an entry under the Unreleased section in the CHANGELOG.md? Entry
      should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md?
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help?
- [ ] Comment-based help added/updated?
- [ ] Localization strings added/updated in all localization files as appropriate?
- [x] Examples appropriately added/updated?
- [ ] Unit tests added/updated?
      See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible)?
      See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to
      [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)
      and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md)?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1208)

### CODE REVIEW

**Comment by johlju** [comment]
@wsmelton Thank you for fixing this! 😃  Just minor comments.

**Comment by wsmelton** [comment]
Curious to know why the built in review features on GitHub are not used instead of a 3rd party tool? I have not submitted PRs to other major projects within MS so unsure if this is common tool or not. It is interesting.

The fact yall also validate a line is only 80 characters wide for markdown is just ridiculous to me as well. This is not coded language and has built in ability to wrap the line for viewing. But is what it is.

Anyway, `InstanceName` is the correct property name:
image

**Comment by wsmelton** [comment]
*[a discussion](https://reviewable.io/reviews/powershell/sqlserverdsc/1208#-LLDhiK2-2ekvdJZJ7m7:-LLF-Q-P55z-_1Md8WdL:bg1qf7f) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

There are merge conflicts since your PR was not based on the latest changes. Could you please rebase against branch dev using `git rebase` (not by using `git pull` or `git merge`, to keep the commit history). If you don't know how to rebase your local dev and working branch, please look at how to [Resolve merge conflicts](https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts).
Let me know if you need any assistance.
</blockquote></details>

Ha, that documentation is backwards to how Git is documented on remotes (e.g. origin should be my fork and not the upstream remote, this goes against every example in the documentation). I'll have to read through that a few times to make sure I don't break my branch.

---

**Comment by johlju** [comment]
The comment from review got strange, commenting here instead.

These are the commands I would have run.

```powershell
git checkout dev
git fetch upstream dev
git rebase upstream/dev
git push origin dev --force
git checkout createag-example-updates
git rebase origin/dev
# fix any merge conflicts, run `git rebase --continue` as necessary 
# When there are no more conflicts. continue with the next row.
git push origin createag-example-updates --force
```

**Comment by johlju** [comment]
At any time during rebase, while there is a conflict, you can abort by using `git rebase --abort`. Also, if for some reason there are nothing to commit when you fix a merge conflict, it can happen if the files are changed to exactly what are already being tracked (is committed), you can use `git rebase --skip`. But only do that if there are nothing to stage for commit.
The last could happen if there was a problem with a rebase prior, and commits was added manually.

**Comment by wsmelton** [comment]
You will have to just close this PR as the branch is messed up now and I can't get it to revert cleanly. I'll come back around and do a new PR at some point.

**Comment by johlju** [comment]
@wsmelton I rebeased it for you, hope you don't mind. Love to get this PR through. 🙂

**Comment by johlju** [comment]
@wsmelton Missed the question you asked in https://github.com/PowerShell/SqlServerDsc/pull/1208#issuecomment-416920555. 

I personally think Reviewable is far superior to GitHub review, and gives you so much more control over the conversations. DSC Resource Kit is using Reviewable, not sure other repositories does. Just last week GitHub added that you can resolve review comments, so they slowly getting better.

The 80 char limit in markdown makes it easier to read the markdown when reviewing the raw files.

**Comment by wsmelton** [comment]
How did you get it to reset?

**Comment by johlju** [comment]
I just ran the commands I posted above, except not pushing dev to your fork since I don't have permission. The rebase replayed your commits over the updated dev branch.

**Comment by johlju** [comment]
Although. Some commit did not want to stage any changes, so I skipped those commits (the changes was already correct by a previous commit).

**Comment by johlju** [comment]
Just waiting for the tests to pass, then I merge this.

**Comment by johlju** [comment]
@wsmelton do you have time to resolve the tests that failed? https://ci.appveyor.com/project/PowerShell/sqlserverdsc/build/9.0.448.0?fullLog=true#L1832

**Comment by johlju** [comment]
@wsmelton I resolved the problem in the examples files, hopefully the tests passes this time.

**Comment by johlju** [comment]
Closing and reopening to kick off the tests again, some error unrelated to this change occurred.

**Comment by johlju** [comment]
@wsmelton this is merged now! Thanks for you help fixing this! 😃

**Pull request merged**
