### PR TITLE
SqlServerEndpoint : Add integration test

### LINKED ISSUE #744: SqlServerEndpoint: Integration test is missing for this resource
**Details of the scenario you tried and the problem that is occurring:**
We should add an integration test for this resource.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by mdaniou**
#### Pull Request (PR) description

Add integration test for the resource

#### This Pull Request (PR) fixes the following issues

- Fixes #744

#### Task list

- [X] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1272)

### CODE REVIEW

**Comment by johlju** [comment]
Yeah, it didnät break, but a bit it got a bit messed up. 🙂  No worries, if you have a look at the files you see that you have an extra example file and the README.md. CLean that upp by adding more commits and everything should be fine. :)

I think it got messed up because you reverted your "debug" commits instead of removing them entirely (with `git rebase -i`).
Also, it looks like you did not do a `git rebase`, but a `git pull` or `git merge` (as can seen by the merge commit `Merge branch 'dev' into mdaniou/SqlServerEndpointIntegrationTest`). Try to use `git rebase` which is simple when you get the hang of it. 😄 Look here for more information https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts

**Comment by johlju** [comment]
The README.md got messed up to 🙂  Let me know when you cleaned it up (by pushing more commit I think is the fastest to resolve it) and I will continue the review 😄

**Comment by johlju** [comment]
If you get stuck let me know and I will help out! 🙂

**Comment by mdaniou** [comment]
I have clicked on Update Branch and I think it did the job.
I really need to look into the rebase mecanism ...

**Comment by johlju** [comment]
> I have clicked on Update Branch and I think it did the job.

It does. I normally squash the commits in the PR any way. It just don't keep the commit history if we want to merge the commits as is.

> I really need to look into the rebase mechanism ...

Usually it is easy. First make sure you have a remote name to the upstream and your fork of the upstream.

```
git remote -v
git remote add origin https://github.com/PowerShell/SqlServerDsc
git remote add my https://github.com/mdaniou/SqlServerDsc
```

Then to rebase, the steps I use is as follows

```
git checkout dev
git fetch origin dev
git rebase origin/dev
git push my dev --force
git checkout working_branch_name
git rebase my/dev
# Fix merge conflicts, and stage the conflicts (with `git add *` or similiar).
git rebase --continue
# If new merge conflicts fix and do the previous command again until there are no more conflicts.
```

**Comment by johlju** [comment]
@mdaniou Waiting for the tests to pass then I will merge this.

**Pull request merged**
