### PR TITLE
SqlAlias: Updated DSC Resource tests with Unit Test Template Version: 1.2.1

### LINKED ISSUE #999: SqlServerDsc: Update unit tests to use the same (newest) unit test template
**Details of the scenario you tried and the problem that is occurring:**
Some of the unit tests are using an old unit test template. Suggest we update all the unit tests to use the latest template.

https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by TraGicCode**
**Pull Request (PR) description**
Updating the Unit tests for DSC Resources to utilize Unit Test Template Version: 1.2.1

**This Pull Request (PR) fixes the following issues:**
This will partly fix the issue #999 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1063)

### CODE REVIEW

**Comment by TraGicCode** [comment]
Hey @johlju ,

Before i troll off and update all DSC Resources within this module to follow the latest unit test template can you take a look at what i did for the SqlAlias DSC resource in this PR and confirm if i'm doing what is expected?  I essentially just copy and pasted the tests into the new template and also needed to remove all the references to `-ModuleName $script:DSCResourceName`.

**Comment by johlju** [comment]
Great work here! Thanks for looking into changing these! :smile:  
It's looking good. Just a few minor comments.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[Tests/Unit/MSFT_SqlAlias.Tests.ps1, line 1 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1063#-L7OiSj4nbieUMWxJ7bR:-L7OiSj4nbieUMWxJ7bS:b-1qno52) ([raw file](https://github.com/powershell/sqlserverdsc/blob/4125025dc0a301d7a04c8b14a2e75fb6d90793e2/Tests/Unit/MSFT_SqlAlias.Tests.ps1#L1)):*
> ```PowerShell
> <#
> ```

This comment block can be removed.

---

*[Tests/Unit/MSFT_SqlAlias.Tests.ps1, line 80 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1063#-L7OicgbgECAh26AQdnw:-L7OicgbgECAh26AQdnx:b-n4i4zd) ([raw file](https://github.com/powershell/sqlserverdsc/blob/4125025dc0a301d7a04c8b14a2e75fb6d90793e2/Tests/Unit/MSFT_SqlAlias.Tests.ps1#L80)):*
> ```PowerShell
> 
>         Describe 'SqlAlias/Get-TargetResource' {
>             BeforeEach {
> ```

This can be removed if there are no code that can be moved into them. Throughout.

---

*[Tests/Unit/MSFT_SqlAlias.Tests.ps1, line 84 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1063#-L7OikHaiwFhJXgBylpf:-L7OikHaiwFhJXgBylpg:b-n4i4zd) ([raw file](https://github.com/powershell/sqlserverdsc/blob/4125025dc0a301d7a04c8b14a2e75fb6d90793e2/Tests/Unit/MSFT_SqlAlias.Tests.ps1#L84)):*
> ```PowerShell
>             }
> 
>             AfterEach {
> ```

This can be removed if there are no code that can be moved into them. Throughout.

---

*[Tests/Unit/MSFT_SqlAlias.Tests.ps1, line 1173 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1063#-L7OixIuMYqswNF_Mvb1:-L7OixIuMYqswNF_Mvb2:bxdajwi) ([raw file](https://github.com/powershell/sqlserverdsc/blob/4125025dc0a301d7a04c8b14a2e75fb6d90793e2/Tests/Unit/MSFT_SqlAlias.Tests.ps1#L1173)):*
> ```PowerShell
>             }
>         }
>         Describe "SqlAlias\Test-TargetResource" {
> ```

I suggest we separate the describe blocks with a blank row.

---

*[Tests/Unit/MSFT_SqlAlias.Tests.ps1, line 1173 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1063#-L7OjBRD8_HUyurS2qVo:-L7OjBRD8_HUyurS2qVp:butqlk5) ([raw file](https://github.com/powershell/sqlserverdsc/blob/4125025dc0a301d7a04c8b14a2e75fb6d90793e2/Tests/Unit/MSFT_SqlAlias.Tests.ps1#L1173)):*
> ```PowerShell
>             }
>         }
>         Describe "SqlAlias\Test-TargetResource" {
> ```

Single quotes on the description of the Describe-blocks. Throughout.

---

*[Tests/Unit/MSFT_SqlAlias.Tests.ps1, line 1350 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1063#-L7OjSPeNPkzbOBIRA0j:-L7OjSPeNPkzbOBIRA0k:bpt5so9) ([raw file](https://github.com/powershell/sqlserverdsc/blob/4125025dc0a301d7a04c8b14a2e75fb6d90793e2/Tests/Unit/MSFT_SqlAlias.Tests.ps1#L1350)):*
> ```PowerShell
> {
>     Invoke-TestCleanup
> }
> ```

Tests are failing because there should be a blank row at the end of the script.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1063#-:-L7OjagsC7p2Lyl7v0cw:b-v11h3z)*

**Comment by TraGicCode** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[Tests/Unit/MSFT_SqlAlias.Tests.ps1, line 1 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1063#-L7OiSj4nbieUMWxJ7bR:-L7PR0IQ1IDCNV_pS0-N:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/4125025dc0a301d7a04c8b14a2e75fb6d90793e2/Tests/Unit/MSFT_SqlAlias.Tests.ps1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This comment block can be removed.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_SqlAlias.Tests.ps1, line 80 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1063#-L7OicgbgECAh26AQdnw:-L7PRQtXSK9u0zxSQVJ5:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/4125025dc0a301d7a04c8b14a2e75fb6d90793e2/Tests/Unit/MSFT_SqlAlias.Tests.ps1#L80)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This can be removed if there are no code that can be moved into them. Throughout.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_SqlAlias.Tests.ps1, line 84 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1063#-L7OikHaiwFhJXgBylpf:-L7PRRo5UJQPihoyAYC4:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/4125025dc0a301d7a04c8b14a2e75fb6d90793e2/Tests/Unit/MSFT_SqlAlias.Tests.ps1#L84)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This can be removed if there are no code that can be moved into them. Throughout.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_SqlAlias.Tests.ps1, line 1173 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1063#-L7OixIuMYqswNF_Mvb1:-L7PRcgBDjnjnDpLwI0Z:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/4125025dc0a301d7a04c8b14a2e75fb6d90793e2/Tests/Unit/MSFT_SqlAlias.Tests.ps1#L1173)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I suggest we separate the describe blocks with a blank row.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_SqlAlias.Tests.ps1, line 1173 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1063#-L7OjBRD8_HUyurS2qVo:-L7PTrPuABYKr2_Xw-yb:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/4125025dc0a301d7a04c8b14a2e75fb6d90793e2/Tests/Unit/MSFT_SqlAlias.Tests.ps1#L1173)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Single quotes on the description of the Describe-blocks. Throughout.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_SqlAlias.Tests.ps1, line 1350 at r1](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1063#-L7OjSPeNPkzbOBIRA0j:-L7PUL3L_85n4CQPfw1t:b-896fix) ([raw file](https://github.com/powershell/sqlserverdsc/blob/4125025dc0a301d7a04c8b14a2e75fb6d90793e2/Tests/Unit/MSFT_SqlAlias.Tests.ps1#L1350)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Tests are failing because there should be a blank row at the end of the script.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1063)*

**Comment by TraGicCode** [comment]
I think i should remove the 'Fixes' to leave the issue open since it is an issue for ALL tests that are not on the latest template.

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1063#-:-L7PasgLF1dDzUy0jggN:bnfp4nl)*

**Comment by johlju** [comment]
@TraGicCode Yes, we should remove fixes from this PR as it will auto-close the issue. I can do that now, before I merge.

**Comment by johlju** [comment]
@TraGicCode To quick on the LGTM again :/ I forgot that we need a entry in the change log. Also, I apologize, I should have asked you if you wanted to add the rest of the tests to the same PR, I just assumed I would merge this PR once all looked good. So, do you want me to merge this PR with just the SqlAlias tests and send in a new PR for the rest (or individually), or do you want to correct all other test on this PR as well? Either is fine with me. Sorry again.

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1063#-L7PdO8KonAZObO3APHZ:-L7PdO8Lq4LhHaM0DRJc:bukrlox) (no related file):*
Please add this change to Unreleased section of the README.md.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1063)*

**Comment by TraGicCode** [comment]
I think we should merge them in 1 by 1.  The reason i saw this is because i doubt i have time to do them all and i wouldn't want a long lived branch around.  These should be short lived because if someone merges a new feature it will cause a huge merge conflict and require redoing the work.  Make sense?

**Comment by johlju** [comment]
@TraGicCode Sounds good to me! 😄  I could split the issue up into multiple issues, one for each test that hasn't got the correct template. Then we can resolve the issues one by one (so they can close on merge as well).

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sqlserverdsc/1063#-:-L7PxVEIakAAZw8nmf1W:bnfp4nl)*

**Pull request merged**
