### PR TITLE
xSQLServerNetwork: Add PsDscRunAsCredential parameter to example

### PR DESCRIPTION
**Pull request by pesetskyps**
**Pull Request (PR) description**
- Changes to xSQLServerNetwork
  - added sysadmin account parameter usage to the examples

**This Pull Request (PR) fixes the following issues:**
n/a

**Task list:**

- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/840)

### CODE REVIEW

**Comment by johlju** [comment]
Thanks for sending in this PR. :smile: You sent in the PR towards the master branch, I switched it to the dev branch.

You need to rebase your branch against the dev branch. Becuase you are missing entries in the change log. Please see [Resolve Merge Conflicts](https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts) here to see how that is done. Please use `git rebase` (and do not use `git merge` or `git pull`).

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Examples/Resources/xSQLServerNetwork/1-EnableTcpIpWithStaticPort.ps1, line 28 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/840#-Ku_wr1GiSZPfz6yLOEG:-Ku_wr1GiSZPfz6yLOEH:busf57o) ([raw file](https://github.com/powershell/xsqlserver/blob/1edcd9a64c3edb1554af80db9430cbead0760882/Examples/Resources/xSQLServerNetwork/1-EnableTcpIpWithStaticPort.ps1#L28)):*
> ```PowerShell
>             TCPPort         = 4509
>             RestartService  = $true
>             PsDscRunAsCredential = $SysAdminAccount
> ```

Could you please add the same for the other example as well? 

You don't have to create a new PR, just push changes into your working branch in your fork, and the PR will update automatically.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/840#-:-Ku_w5UI2hJfUGdHdP8E:bhqe0kn)*

**Comment by johlju** [comment]
@pesetskyps Please sign the CLA for me to be able to merge these changes (once the review comments are resolved).

**Comment by pesetskyps** [comment]
signed in cla, pushed edit for the second example, rebased (not sure if it was corrent, needed to use the git push -f in the end)
Let me know in case of any issues, thanks

**Comment by pesetskyps** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Examples/Resources/xSQLServerNetwork/1-EnableTcpIpWithStaticPort.ps1, line 28 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/840#-Ku_wr1GiSZPfz6yLOEG:-KucV2ZOhhjB5uuMvMZq:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/1edcd9a64c3edb1554af80db9430cbead0760882/Examples/Resources/xSQLServerNetwork/1-EnableTcpIpWithStaticPort.ps1#L28)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Could you please add the same for the other example as well? 

You don't have to create a new PR, just push changes into your working branch in your fork, and the PR will update automatically.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/840)*

**Comment by johlju** [comment]
Reviewed 1 of 2 files at r3, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CHANGELOG.md, line 4 at r5](https://reviewable.io:443/reviews/powershell/xsqlserver/840#-KuegjNKPEbZsbxtZvxW:-KuegjNKPEbZsbxtZvxX:bmxyb93) ([raw file](https://github.com/powershell/xsqlserver/blob/33adfd64af8dab3459a4c6db02f7d319bfc1c1e3/CHANGELOG.md#L4)):*
> ```Markdown
> 
> ## Unreleased
> - Changes to xSQLServerNetwork
> ```

Please add your entries to the end of the Unreleased section. 

And please make sure to leave a blank row after the section header. Otherwise the tests will fail.
https://ci.appveyor.com/project/PowerShell/xsqlserver/build/6.0.1642.0#L1434

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/840)*

**Comment by johlju** [comment]
You did correct using force on the `git push` command. It is necessary, The rebase worked correctly. Just a few comments more.

**Comment by johlju** [comment]
Closing and re-opening this PR to try to get the correct CLA status.

**Comment by johlju** [comment]
@pesetskyps Do you have time to resolve the review comments?

**Comment by pesetskyps** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 4 at r5](https://reviewable.io:443/reviews/powershell/xsqlserver/840#-KuegjNKPEbZsbxtZvxW:-KuzdLqC8mkzvA-saDXc:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/33adfd64af8dab3459a4c6db02f7d319bfc1c1e3/CHANGELOG.md#L4)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please add your entries to the end of the Unreleased section. 

And please make sure to leave a blank row after the section header. Otherwise the tests will fail.
https://ci.appveyor.com/project/PowerShell/xsqlserver/build/6.0.1642.0#L1434
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/840)*

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 4 at r5](https://reviewable.io:443/reviews/powershell/xsqlserver/840#-KuegjNKPEbZsbxtZvxW:-Kuzgf2UMtoqNyHg6WsW:buzi2y2) ([raw file](https://github.com/powershell/xsqlserver/blob/33adfd64af8dab3459a4c6db02f7d319bfc1c1e3/CHANGELOG.md#L4)):*
<details><summary><i>Previously, pesetskyps (Pavel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Could you please move your entries to the end of the Unreleased section? After line 101. 

We add new entries in chronological order.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/840)*

**Comment by pesetskyps** [comment]
Can you take a look?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/840#-:-Kv2-4YNICXLOF4KB_CF:bjwuuv2)*

**Comment by pesetskyps** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CHANGELOG.md, line 4 at r5](https://reviewable.io:443/reviews/powershell/xsqlserver/840#-KuegjNKPEbZsbxtZvxW:-Kv2-Y5CZ90-xi8XGqr8:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/33adfd64af8dab3459a4c6db02f7d319bfc1c1e3/CHANGELOG.md#L4)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Could you please move your entries to the end of the Unreleased section? After line 101. 

We add new entries in chronological order.  
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/840)*

**Comment by johlju** [comment]
This looks good now. But for the tests to run, and I to be able to merge, you need to resolve the merge conflicts in the CHANGELOG.md. Please see the below link on how to use `git rebase` to resolve the merge conflicts.  Please use `git rebase` (do not use `git merge` or `git pull`)
https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/840#-:-Kv2g941LO2l7BcYN3Vl:b-ruxjjc)*

**Comment by johlju** [comment]
@pesetskyps Please resolve the merge conflicts. And also make sure to move the entries in the CHANGELOG.md back to the Unreleased section after rebase. _This is due to the recent release  of the module._

**Comment by johlju** [comment]
I will label this as abandoned for the mean time until either the contributor pick this up again or another contributor continue the work.

**Comment by johlju** [comment]
Closing this as there is a new PR #963 that will take this to the finish line. That PR is based on this one. @pesetskyps Thanks for your contribution!

**Pull request closed without merging**
