### PR TITLE
Fixed examples README

### PR DESCRIPTION
**Pull request by adamrushuk**
#### Pull Request (PR) description
Added a link to the new xADObjectPermissionEntry examples in xActiveDirectory, fixed a broken link and a typo.

#### This Pull Request (PR) fixes the following issues
n/a

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1241)

### CODE REVIEW

**Comment by johlju** [comment]
@adamrushuk This looks great, thank you for fixing this. Much appreciated! I will merge this as soon as I have merged another PR (waiting for the tests to pass on that). Sorry it took so long for me to review this, but have been a busy last two months.

**Comment by adamrushuk** [comment]
No worries @johlju, I appreciate how busy you've been :)

**Comment by johlju** [comment]
FYI. There are currently a problem with the tests not passing, unrelated to this PR. I looking into it why it doesn't work, but it's gonna take a while. Will merge this PR as soon as the test are able to pass.

**Comment by adamrushuk** [comment]
That's fine. Thanks for the heads-up.

**Comment by johlju** [comment]
@adamrushuk I thought I would helped by adding a entry to the change log, and pushed to your working branch before I merged this change. Hope you don't mind. But that made the CLA bot see another change and requests the CLA to be signed. So for me to be able to merge this you need to sign the CLA by clicking *sign now* in the comment above. 
It entirely up to you if you want to sign or not. 🙂

**Comment by adamrushuk** [comment]
Awesome, thanks @johlju

**Pull request merged**
