### PR TITLE
xSQLServer: MSFT_xSQLDBRestore. New resource to restore databases

### PR DESCRIPTION
**Pull request by arcotek-ltd**
**Pull Request (PR) description**

**This Pull Request (PR) fixes the following issues:**

**Task list:**

- [ ] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/956)

### CODE REVIEW

**Comment by johlju** [comment]
@arcotek-ltd you did not actually PR in any changes. There are zero changes files in this PR.

**Comment by johlju** [comment]
@arcotek-ltd let me know if you need help PR in your changes. Happy to help. 😄

**Comment by arcotek-ltd** [comment]
Hi @johlju,

I was trying to do it quickly and couldn't find any obvious place to add the code (still can't). I guess I need to do some reading. Probably best to close off this PR for now and I'll have another go when I've had a chance to look for and read the docs on how to do it.

**Comment by johlju** [comment]
No worries. Please, give it a try again. You must add code locally on you machine. 

You can read hear; https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md

1. Click 'Fork'-button on top of this page (to the right)
2. Install Git (and configure it, see link above)
3. Clone this repo and add a remote to your fork
   ```
   cd c:\source
   git clone https://github.com/PowerShell/SqlServerDsc # get the code from this repo
   cd SqlServerDsc
   git remote add my https://github.com/arcotek-ltd/SqlServerDsc # Add a remote to your fork
   ```
4. Create a working branch (so you can have several ongoing project from the same base, dev-branch) by running `git checkout -b my-branch-name'.
5. Add code by copy in updated files in the local repo directory 'c:\source\SqlServerDsc'. Preferably use Visual Studio Code (whihch has good git support) to edit the code.
6. Use either VS Code to commit the changes. Or use `git add *` from PowerShell/cmdline when you are in the local repo folder.
7. Push you changes to your _fork_ by running `git push my my-branch-name'. 
8. Go to your fork on Github https://github.com/arcotek-ltd/SqlServerDsc and choose your working branch in the branch list drop-down, and then click on the button 'New pull request'. 

Follow the instructions on the pages, and you will get a PR here.  😄 Let me know if you getting stuck. Happy to help.

**Pull request closed without merging**
