### PR TITLE
SqlSetup: Tempdb File Configuration

### LINKED ISSUE #1167: SqlSetup: Missing Configuration Feature/Options :  Tempdb File Configuration
#### Details of the scenario you tried and the problem that is occurring

This issue is created to bring some improvements to the SqlSetup DSC Configuration. The idea is to report all the missing options in the resource to be allow the installation of all the features and to use all the options available in the SQL Server installer.

Options to add to the DSC Resource :

/SQLTEMPDBFILECOUNT
/SQLTEMPDBFILESIZE
/SQLTEMPDBFILEGROWTH
/SQLTEMPDBLOGFILESIZE
/SQLTEMPDBLOGFILEGROWTH

#### The DSC configuration that is using the resource (as detailed as possible)

SqlSetup

#### Version of the operating system and PowerShell the target node is running

Windows Server 2012/2012R2/2016

#### SQL Server edition and version the target node is running

SQL Server 2016/2017

#### What SQL Server PowerShell modules, and which version, are present on the target node.

Most recent version

#### Version of the DSC module you're using, or write 'dev' if you're using current dev branch

Most recent version

### PR DESCRIPTION
**Pull request by mdaniou**
#### Pull Request (PR) description

Adding the configuration of the tempdb files during installation.

/SQLTEMPDBFILECOUNT
/SQLTEMPDBFILESIZE
/SQLTEMPDBFILEGROWTH
/SQLTEMPDBLOGFILESIZE
/SQLTEMPDBLOGFILEGROWTH

#### This Pull Request (PR) fixes the following issues
- Fixes #1167

#### Task list

- [X] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [X] Resource documentation added/updated in README.md.
- [X] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [X] Comment-based help added/updated.
- [X] Localization strings added/updated in all localization files as appropriate.
- [X] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sqlserverdsc/1242)

### CODE REVIEW

**Comment by mdaniou** [comment]
@johlju Hi Johan, I get this error : 
Failed to connect to the instance APPVYR-WIN\DSCSQL2016 within the timeout period of 120 seconds.

I think that I should rerun the integration test. How can I do that please ? :)

**Comment by johlju** [comment]
Easiest by closing an reopening thr PR. On the PR here you have “Close PR”, when you press that you get “Reopen PR”, press that and the PR opens up again as the tests should kick off again :)

**Comment by mdaniou** [comment]
Cool thanks.

**Comment by johlju** [comment]
@mdaniou It seems there is a problem running the unit tests in the container2. Seems there is a problem that is not handle by the container logic. I haven't time to look at it now. I will not be able to help out in the coming weeks as I will be traveling and and going on vacation.

Can you confirm that the unit tests work locally?

**Comment by mdaniou** [comment]
@johlju To be honest I can't confirm that it works locally.

**Comment by mdaniou** [comment]
I have reverted the change to the unit test to see what happens.

**Comment by johlju** [comment]
Actually it is only the unit test that runs in the containers. The integration test runs in the main build worker 
So I was just curious if the unit test worked locally. If it does then the container handling has some bug in it :)
I can help debug this but I’m gonna be occupied by other things the next two weeks :/

**Comment by mdaniou** [comment]
Sorry for the late answer.
As the changes were minimal, I didn't test it before submitting the PR :)

I'll take the time to do that answer your question. Maybe I'll figure what's going on.

**Comment by johlju** [comment]
@mdaniou Looked into this now. If you run the unit tests locally they fail. Can you please run the below and see if you can find why the unit tests fail?

```powershell
.\Assert-TestEnvironment.ps1
Invoke-Pester .\Tests\Unit\MSFT_SqlSetup.Tests.ps1 -CodeCoverage .\DSCResources\MSFT_SqlSetup\MSFT_SqlSetup.psm1
```

**Comment by mdaniou** [comment]
Hi,

I finally take some time to check that.
It seems like I need to create the tempdb database in the block below with some file

`
        $mockConnectSQL = {
            return @(
                (
                    New-Object -TypeName Object |
                        Add-Member -MemberType NoteProperty -Name 'LoginMode' -Value $mockSqlLoginMode -PassThru |
                        Add-Member -MemberType NoteProperty -Name 'Collation' -Value $mockSqlCollation -PassThru |
                        Add-Member -MemberType NoteProperty -Name 'InstallDataDirectory' -Value $mockSqlInstallPath -PassThru |
                        Add-Member -MemberType NoteProperty -Name 'BackupDirectory' -Value $mockDynamicSqlBackupPath -PassThru |
                        Add-Member -MemberType NoteProperty -Name 'SQLTempDBDir' -Value $mockDynamicSqlTempDatabasePath -PassThru |
                        Add-Member -MemberType NoteProperty -Name 'SQLTempDBLogDir' -Value $mockDynamicSqlTempDatabaseLogPath -PassThru |
                        Add-Member -MemberType NoteProperty -Name 'DefaultFile' -Value $mockSqlDefaultDatabaseFilePath -PassThru |
                        Add-Member -MemberType NoteProperty -Name 'DefaultLog' -Value $mockSqlDefaultDatabaseLogPath -PassThru |
                        Add-Member -MemberType ScriptProperty -Name Logins -Value {
                            return @( ( New-Object -TypeName Object |
                                    Add-Member -MemberType NoteProperty -Name 'Name' -Value $mockSqlSystemAdministrator -PassThru |
                                    Add-Member -MemberType ScriptMethod -Name ListMembers -Value {
                                        return @('sysadmin')
                                    } -PassThru -Force
                                ) )
                        } -PassThru -Force
                )
            )
        }`

I admit that I struggle with that. I would need some help ... :(

**Comment by mdaniou** [comment]
Hi,

I have fixed the issue with the UNIT test.

Now I have a confusing error on the INTEGRATION test :
Login failed for user 'APPVYR-WIN\SqlInstall'. Reason: Server is in single user mode. Only one administrator can connect at this time.

Any idea on this ?

Thanks

**Comment by mdaniou** [comment]
Closing and directly reopening the PR to kick off the tests again.

**Comment by johlju** [comment]
Please rebase to get the recent merge. That should solve the problem with the failing tests too.

**Comment by mdaniou** [comment]
I have clicked on "Update branch", hope this is enough

**Comment by johlju** [comment]
Yes that worked, looking good. I will review as soon as I have time. :)

**Comment by johlju** [comment]
@mdaniou Really awesome work on this!

**Comment by mdaniou** [comment]
Thanks ! It feel great to have this closed finally ! :)

**Pull request merged**
